// ===== UI LABELS — EN / BM / ZH =====
// Split from calculators.js for maintainability

export const L = {
  en: {
    tools: 'Property Tools',
    phase1Tools: 'Pre-signing toolkit',
    phase1ToolsSub: "Don't sign blind",
    toolScreenTile: 'Screen tenant',        toolScreenTileSub: 'Trust check',
    toolAuditTile: 'Audit agreement',       toolAuditTileSub: 'Clause scan',
    toolStampTile: 'Stamp duty',            toolStampTileSub: 'SDSAS 2026',
    exportPdf: 'Export PDF',                exporting: 'Preparing PDF…',
    stampSavedToCase: 'Saved to case memory',
    // === TOOL 1 — Payment Discipline Scan (Bloomberg-not-FICO) ===========
    screenTitleV2: 'Payment Discipline Scan',
    screenDescV2: 'Show 4 app screens at the viewing. No uploads, no bank statements.',
    screenSubDnaFooter: 'Find.ai surfaces payment behaviour. The decision to enter tenancy rests entirely with the landlord.',
    screenTenantSection: 'Tenant at the viewing',
    screenTenantName: 'Full name (per MyKad)',
    screenTenantIC: 'IC last 4 digits',
    screenTenantPhone: 'Mobile number',
    screenConsentTitle: 'Consent (tick at the viewing)',
    screenConsentText: 'Tenant has given verbal consent to share these payment-app screens with the landlord for this tenancy application only. Data deleted 12 months after tenancy ends.',
    screenStartScan: 'Start 4-step scan',
    screenStepElec: 'Step 1 · Electricity',
    screenStepMobile: 'Step 2 · Mobile postpaid',
    screenStepInternet: 'Step 3 · Home internet',
    screenStepWildcard: 'Step 4 · One voluntary subscription',
    screenElecApps: 'myTNB · mySESB · SEB Cares',
    screenMobileApps: 'MyMaxis · CelcomDigi · U Mobile · Yes · Yoodo',
    screenInternetApps: 'MyUnifi · MyMaxis Home · Time · Yes Home',
    screenAccountName: 'Name on the account',
    screenOnTime: 'Months paid on-time (of last 12)',
    screenTenure: 'Account tenure',
    screenArrears: 'Any arrears / disconnection showing now?',
    screenVendor: 'Which app / vendor?',
    screenVendorHint: 'e.g. Unifi, Maxis Home, Time',
    screenWildcardHint: 'Pick one voluntary recurring auto-debit the tenant has.',
    screenWildcardCategories: {
      waterFilter: 'Water filter (Coway / Cuckoo / other)',
      takaful: 'Insurance / Takaful',
      streaming: 'Streaming (Netflix / Spotify / Astro / iQiyi…)',
      gym: 'Gym membership',
      ewallet: 'E-wallet auto-reload (TnG / GrabPay / Boost)',
      other: 'Other recurring auto-debit',
    },
    screenTenureBuckets: {
      lt6: 'Less than 6 months',
      sixTo12: '6–12 months',
      oneTo2y: '1–2 years',
      twoTo5y: '2–5 years',
      gt5y: 'More than 5 years',
    },
    screenSkip: 'Skip (not applicable)',
    screenNext: 'Next',
    screenBackStep: 'Back',
    screenReview: 'Review',
    screenIndexLabel: 'Payment Discipline Index',
    screenCoverage: 'Based on {n} of 4 signals',
    screenNoVerdict: 'This is not a recommendation. Numbers describe behaviour, not fitness.',
    screenFinish: 'Finish scan',
    screenExportPdf: 'Export Scan PDF',
    screenSaveToCase: 'Save to case memory',
    screenSavedToCase: 'Saved to case memory',
    screenNameMismatch: 'Name on account differs from MyKad',
    screenNameMatch: 'Name matches MyKad',
    screenPartialMatch: 'Partial name match',
    screenArrearsFlag: 'Current arrears showing on this account',
    screenYes: 'Yes', screenNo: 'No',
    screenSignalElectricity: 'Electricity',
    screenSignalMobile: 'Mobile',
    screenSignalInternet: 'Internet',
    screenSignalWildcard: 'Voluntary subscription',
    // =====================================================================
    stampTitle: 'Stamp Duty Calculator', stampDesc: 'Tenancy agreement stamp duty',
    yieldTitle: 'Rental Yield Calculator', yieldDesc: 'Is your property worth it?',
    screenTitle: 'Tenant Screening', screenDesc: 'Check tenant risk before signing',
    healthTitle: 'Agreement Health Check', healthDesc: 'Is your agreement protecting you?',
    monthlyRent: 'Monthly Rent (RM)', leaseDuration: 'Lease Duration',
    years: ['1 year', '2 years', '3 years', '5 years'],
    stampResult: 'Stamp Duty Payable (SDSAS 2026)', stampExempt: 'Exempt — no stamp duty required',
    stampNote: 'Unstamped agreements cannot be used as evidence in court.',
    stampWho: 'Usually paid by tenant, but negotiable.',
    stampDeadline: 'Must stamp within 30 days of signing. Late = penalty up to 100%.',
    stampPerUnit: 'per RM250 unit of annual rent',
    sdsasNote: 'Self-assessment system (SDSAS) effective Jan 2026. RM2,400 exemption removed. You calculate and pay via MyTax.',
    oldDuty: 'Old Rules (Pre-2026)', dutyIncrease: 'Increase',
    wasExempt: 'This rental was previously EXEMPT (under RM2,400/yr). Under 2026 rules, stamp duty now applies.',
    vaultTitle: 'Photo Proof', vaultDesc: 'Protect yourself — snap, lock, done',
    vaultAddress: 'Property / Condo Name', vaultAddressHint: 'e.g. Lakefront Residence, Cyberjaya',
    vaultUnit: 'Unit Number', vaultType: 'What is this for?', vaultSelectType: 'Select one',
    vaultCheckIn: 'Tenant moving in', vaultCheckOut: 'Tenant moving out', vaultDamage: 'Recording damage', vaultGeneral: 'Other',
    vaultUpload: 'Add Photos', vaultUploadHint: 'Take photos or choose from gallery — we lock each one so it can\'t be disputed',
    vaultHashing: 'Locking your photos...', vaultPhotos: 'Your Photos', vaultHash: 'Protection',
    vaultGenerate: 'Create Proof Certificate', vaultVerified: 'LOCKED & PROTECTED',
    vaultCertId: 'Certificate No.', vaultDownload: 'Download Your Certificate',
    vaultLegalNote: 'This certificate proves your photos are original and untampered. It\'s accepted in Malaysian courts under the Evidence Act. Keep your original photos safe — don\'t edit or rename them.',
    annualRent: 'Annual Rent', purchasePrice: 'Purchase Price (RM)',
    monthlyExpenses: 'Monthly Expenses (RM)', expensesHint: 'Maintenance, insurance, assessment, quit rent',
    grossYield: 'Gross Yield', netYield: 'Net Yield',
    annualProfit: 'Annual Net Profit', monthlyProfit: 'Monthly Net Profit',
    verdict: 'Verdict',
    verdictGood: 'Good investment — above market average',
    verdictOk: 'Average — consider if appreciation potential exists',
    verdictWeak: 'Below average — review your rental pricing or expenses',
    calculate: 'Calculate',
    tenantSalary: 'Tenant Monthly Salary (RM)', rentAmount: 'Your Monthly Rent (RM)',
    jobType: 'Employment Type', occupants: 'Number of Occupants', bedrooms: 'Bedrooms in Unit',
    moveReason: 'Reason for Moving', hasGuarantor: 'Has Guarantor?',
    jobs: { permanent: 'Permanent', contract: 'Contract', selfEmployed: 'Self-Employed', unemployed: 'Unemployed/Student' },
    reasons: { leaseEnd: 'Lease ended', work: 'Closer to work', family: 'Family reasons', evicted: 'Evicted / Asked to leave', firstTime: 'First time renting' },
    yes: 'Yes', no: 'No', checkTenant: 'Screen Tenant',
    riskLevel: 'Risk Level', riskLow: 'LOW RISK', riskMed: 'MEDIUM RISK', riskHigh: 'HIGH RISK',
    redFlags: 'Red Flags', greenFlags: 'Green Flags', recommendation: 'Recommendation',
    affordability: 'Affordability Ratio',
    checkAgreement: 'Check Agreement', score: 'Agreement Score', missing: 'Missing Clauses', present: 'Present',
    strong: 'STRONG — Well protected', moderate: 'MODERATE — Some gaps to fix', weak: 'WEAK — Major gaps, high risk',
    clauses: [
      { id: 'latePay', q: 'Late payment penalty clause?' },
      { id: 'deposit', q: 'Security deposit amount specified (2+1)?' },
      { id: 'maintenance', q: 'Maintenance responsibility defined?' },
      { id: 'sublet', q: 'Subletting prohibition included?' },
      { id: 'earlyTermination', q: 'Early termination clause with notice period?' },
      { id: 'inventory', q: 'Check-in/check-out inventory checklist?' },
      { id: 'utility', q: 'Utility transfer & final bill clause?' },
      { id: 'stampDuty', q: 'Stamp duty responsibility stated?' },
      { id: 'renewal', q: 'Renewal terms defined?' },
      { id: 'dispute', q: 'Dispute resolution method stated?' },
    ],
    clauseFix: {
      latePay: 'Add: "Late payment charge of 10% p.a. on outstanding sum after 14 days"',
      deposit: 'Add: "Security deposit of 2 months rent + 0.5 month utility deposit"',
      maintenance: 'Add: "Tenant responsible for wear & tear items. Landlord responsible for structural & major systems"',
      sublet: 'Add: "Tenant shall not sublet, assign or part with possession without written consent"',
      earlyTermination: 'Add: "Either party may terminate with 2 months written notice + forfeiture of deposit"',
      inventory: 'Add: "Detailed inventory with photos to be signed by both parties at check-in and check-out"',
      utility: 'Add: "Tenant to transfer utilities to own name within 14 days. Final bills to be settled before deposit refund"',
      stampDuty: 'Add: "Stamp duty on this agreement shall be borne by the Tenant"',
      renewal: 'Add: "Tenant has first right of renewal with 2 months notice before expiry at revised terms"',
      dispute: 'Add: "Disputes to be referred to mediation before court proceedings"',
    },
    trustTitle: 'CN-MY Trust Link', trustDesc: 'Verify Chinese company before signing lease',
    usccLabel: '18-Digit USCC Code', usccHint: 'Unified Social Credit Code from business license',
    usccInvalid: 'Invalid USCC — must be 18 characters (letters + numbers)',
    companyName: 'Company Name (Chinese)', companyNameEn: 'Company Name (English)',
    paidInCapital: 'Paid-in Capital (RMB)', taxRating: 'Tax Credit Rating',
    taxRatings: { A: 'Grade A — Excellent', B: 'Grade B — Good', C: 'Grade C — Fair', D: 'Grade D — Poor' },
    yearsOp: 'Years in Operation', bizScope: 'Business Scope',
    bizScopes: { manufacturing: 'Manufacturing', trading: 'Trading', logistics: 'Logistics', tech: 'Technology', other: 'Other' },
    abnormalOps: 'On Abnormal Operations List?',
    courtRecords: 'Court/Legal Disputes?',
    generateReport: 'Generate Trust Report',
    trustGrade: 'Trust Grade', trustScore: 'Trust Score',
    trustA: 'GRADE A — Low Risk. Safe to proceed with standard terms.',
    trustB: 'GRADE B — Moderate. Proceed with additional safeguards (guarantor + extra deposit).',
    trustC: 'GRADE C — Elevated Risk. Require bank guarantee or parent company guarantee.',
    trustD: 'GRADE D — High Risk. Not recommended. If proceeding, require full prepayment.',
    riskFactors: 'Risk Factors', positiveFactors: 'Positive Factors',
    trustDisclaimer: 'Advisory report only. Not a credit guarantee. Verify all information independently before signing any agreement.',
    downloadReport: 'Download Trust Report',
    trustLookup: 'Looking up company...', trustFound: 'Company found in database',
    trustNotFound: 'Not in database — enter details manually', trustAutoFill: 'Auto-filled from database',
    trustManual: 'Manual Entry', trustAuto: 'Auto Lookup',
    trustRetry: 'Retry', trustOffline: 'Connection failed — enter details manually',
    trafficGreen: 'GREEN LIGHT — Safe to proceed', trafficYellow: 'YELLOW LIGHT — Proceed with caution', trafficRed: 'RED LIGHT — High risk',
    // MY Company Check
    myCheckTitle: 'MY Company Check', myCheckDesc: 'Verify Malaysian company before signing lease',
    ssmLabel: 'SSM Company Number', ssmHint: '12-digit registration number from SSM',
    ssmInvalid: 'Invalid SSM number — must be 12 digits',
    myCompanyName: 'Company Name', myCompanyType: 'Company Type', myPaidUpCapital: 'Paid-up Capital (RM)',
    myYearsOp: 'Years in Operation', myStatus: 'Company Status', myDirectors: 'Directors',
    myNature: 'Nature of Business', myAddress: 'Registered Address', myCompliant: 'SSM Filings Up to Date',
    myTypes: { 'sdn-bhd': 'Sdn Bhd', 'bhd': 'Berhad', 'llp': 'LLP', 'partnership': 'Partnership', 'sole-prop': 'Sole Proprietorship' },
    myStatuses: { active: 'Active', dormant: 'Dormant', 'struck-off': 'Struck Off', 'winding-up': 'Winding Up' },
    myGenerateReport: 'Generate Company Report', myDownloadReport: 'Download Company Report',
    myDisclaimer: 'Advisory report only. Based on available SSM data. Not a credit guarantee. Verify all information independently before signing any agreement.',
    // Main screen cards
    chatCardTitle: 'Property Q&A', chatCardDesc: 'Ask any landlord, tenant, or buyer question',
    cnCardTitle: 'CN Company Check', cnCardDesc: 'Verify Chinese company (USCC)',
    myCardTitle: 'MY Company Check', myCardDesc: 'Verify Malaysian company (SSM)',
    navTitle: 'Situation Navigator', navDesc: 'Step-by-step guide for property disputes',
    navPick: 'What situation are you facing?',
    navRentDefault: 'Rent Default', navRentDefaultDesc: 'Tenant hasn\'t paid rent',
    navDeposit: 'Deposit Dispute', navDepositDesc: 'Deposit not returned or unfair deductions',
    navEviction: 'Eviction Process', navEvictionDesc: 'Need to remove tenant legally',
    navTimeline: 'Timeline', navCost: 'Estimated Cost', navLaw: 'Legal Basis',
    navStep: 'Step', navAction: 'What to do', navWarning: 'Warning',
    navDocument: 'Document Template', navCopyDoc: 'Copy Template',
    navBack: 'Back to situations',
    bridgeTitle: 'Can I Do This?', bridgeDesc: 'Malaysia property compliance checker',
    bridgePick: 'What do you want to do in Malaysia?', bridgePickSub: 'Select your goal — we\'ll show everything you need',
    bridgeRent: 'Rent Property', bridgeBuy: 'Buy Property', bridgeOperate: 'Operate Business',
    bridgeRentHouse: 'Rent a House / Condo', bridgeRentHouseDesc: 'Residential tenancy as foreigner',
    bridgeRentOffice: 'Rent an Office / Shop', bridgeRentOfficeDesc: 'Commercial lease for business',
    bridgeRentFactory: 'Rent a Factory / Warehouse', bridgeRentFactoryDesc: 'Industrial lease for manufacturing',
    bridgeBuyHouse: 'Buy a House / Condo', bridgeBuyHouseDesc: 'Foreign ownership requirements',
    bridgeBuyLand: 'Buy Land', bridgeBuyLandDesc: 'Agricultural, development, vacant',
    bridgeOpenFnb: 'Open a Restaurant / F&B', bridgeOpenFnbDesc: 'Food business licensing',
    bridgeSetupFactory: 'Set Up a Factory', bridgeSetupFactoryDesc: 'Manufacturing operations',
    bridgeSpecify: 'Tell us more', bridgeSpecifySub: 'Different situations need different licenses',
    bridgeActivity: 'What will you do?', bridgeWhere: 'Where?', bridgeAgriLand: 'Is it on agricultural land?',
    bridgeForeignWorkers: 'Will you bring foreign workers?', bridgeCheckBtn: 'Check My Requirements',
    bridgeYes: 'Yes', bridgeNo: 'No', bridgeNotSure: 'Not Sure',
    bridgeVerdictYes: 'YES — You can do this', bridgeVerdictMaybe: 'CONDITIONALLY YES', bridgeVerdictNo: 'NOT ALLOWED',
    bridgeRequired: 'REQUIRED', bridgeRequiredSub: 'Must have before operating',
    bridgeRecommended: 'RECOMMENDED', bridgeRecommendedSub: 'Strongly advised',
    bridgeDept: 'Department', bridgeTimeline: 'Timeline', bridgeCost: 'Cost',
    bridgeTotalLicenses: 'Total licenses needed', bridgeTotalTime: 'Estimated total time',
    bridgeTotalCost: 'Estimated total cost', bridgeDownload: 'Download Full Checklist',
    bridgeAskAI: 'Ask Find.ai for Help', bridgeBack: 'Back',
    bridgeCNTrap: 'China Assumption Trap',
    bridgeNote: 'Advisory guide only. Requirements may vary by local authority. Consult a licensed advisor.',
    bridgeTimeline2: 'Typical Timeline',
    bridgeManufacturing: 'Manufacturing / Assembly', bridgeManufacturingDesc: 'Producing or assembling products',
    bridgeWarehouse: 'Warehouse / Storage', bridgeWarehouseDesc: 'Storing goods, logistics hub',
    bridgeChemical: 'Chemical / Hazardous', bridgeChemicalDesc: 'Working with chemicals',
    bridgeFoodProcessing: 'Food Processing', bridgeFoodProcessingDesc: 'Food manufacturing or packaging',
    // === PATH D — Tenant Pre-Registration ("Register once, rent anywhere") =====
    regTitle: 'Register once, rent anywhere',
    regDesc: 'Build a trust profile every future landlord sees in 1 second.',
    regStepOf: 'Step {n} of 5',
    regStartCTA: 'Start my profile',
    regAlreadyHave: 'I already have a profile',
    regResume: 'Resume registration',

    regS1Title: 'Verify your phone',
    regS1Sub: 'Any Malaysian mobile — Celcom, Digi, Maxis, Umobile, Yoodo.',
    regS1PhoneLabel: 'Mobile number',
    regS1PhonePlaceholder: '+60 12-345 6789',
    regS1SendOTP: 'Send 6-digit code',
    regS1SendingOTP: 'Sending…',
    regS1OTPLabel: 'Enter the code we sent',
    regS1OTPPlaceholder: '6-digit code',
    regS1Verify: 'Verify',
    regS1Verified: 'Phone verified',
    regS1PhoneInvalid: 'Enter a valid Malaysian mobile number',
    regS1OTPInvalid: 'Code doesn\'t match. {n} tries left.',
    regS1OTPExpired: 'Code expired. Request a new one.',
    regS1Resend: 'Resend code',
    regS1MockNote: 'Demo mode — code is shown in your browser console. Production uses SMS.',

    regS2Title: 'Your identity',
    regS2Sub: 'Used only to match your name to your utility accounts. IC is hashed, never stored in plain form.',
    regS2NameLabel: 'Full name (per MyKad)',
    regS2NamePlaceholder: 'e.g. Siti Aminah Binti Hassan',
    regS2ICLabel: 'IC number (12 digits)',
    regS2ICPlaceholder: '950203-08-1234',
    regS2ICInvalid: 'IC format must be 12 digits (YYMMDD-PB-XXXG)',
    regS2SelfieLabel: 'Live selfie (optional)',
    regS2SelfieHint: 'Adds an extra layer of identity confirmation — skip to add later.',
    regS2SelfieAdd: 'Take selfie',
    regS2SelfieCaptured: 'Selfie captured',

    regS3Title: 'TNB electricity account',
    regS3Sub: 'Type your TNB account number, then drop any recent TNB bill PDF. We match the number to the bill.',
    regS3AccountLabel: 'TNB account number (12 digits)',
    regS3AccountPlaceholder: 'e.g. 2200 1234 5678',
    regS3BillUpload: 'Upload recent TNB bill (PDF or photo)',
    regS3BillUploaded: 'Bill received — {name}',
    regS3BillAmountLabel: 'Last bill amount (RM)',
    regS3BillDateLabel: 'Bill date',
    regS3PaidOnTime: 'Paid on or before due date?',
    regS3Verify: 'Confirm account',
    regS3Verified: 'TNB account verified',
    regS3Skip: 'Skip — add later',

    regS4Title: 'Unifi / Maxis Home internet',
    regS4Sub: 'Same pattern — account number plus one recent bill.',
    regS4ProviderLabel: 'Provider',
    regS4ProviderUnifi: 'Unifi',
    regS4ProviderMaxisHome: 'Maxis Home',
    regS4ProviderTime: 'Time',
    regS4ProviderYesHome: 'Yes Home',
    regS4AccountLabel: 'Account number',
    regS4AccountPlaceholder: 'e.g. ABC12345',
    regS4BillUpload: 'Upload recent bill (PDF or photo)',
    regS4Verify: 'Confirm account',
    regS4Verified: 'Internet account verified',

    regS5Title: 'Consent & finish',
    regS5Sub: 'Your profile is created the moment you tap Create. You control every future share.',
    regS5Consent1: 'I authorize Find.ai to store this profile for tenancy trust purposes under PDPA 2010.',
    regS5Consent2: 'I authorize monthly auto-refresh via my forwarded utility bills (optional).',
    regS5Consent2Sub: 'Keeps your payment history current so landlords always see the latest data.',
    regS5PDPARights: 'You can view, export, or delete your profile at any time (PDPA s.30-34).',
    regS5Create: 'Create my trust profile',
    regS5Creating: 'Creating…',

    regDoneTitle: 'Your profile is live',
    regDoneSub: 'Share this link with any landlord — they see your grade instantly.',
    regDoneGrade: 'Your starter grade',
    regDoneGradeNote: 'Grade improves as payment history builds. Month 6 you\'ll likely be at A.',
    regDoneLink: 'Your shareable link',
    regDoneCopy: 'Copy link',
    regDoneCopied: 'Copied',
    regDoneOpenWA: 'Share via WhatsApp',
    regDoneNext: 'Done',
    regDoneWAMsg: 'Hi — here is my Find.ai tenant profile: {url}\n\nIt takes you 1 tap to see my verified payment history. Revocable anytime.',

    regBack: 'Back',
    regNext: 'Next',
    regSkipStep: 'Skip this step',
    regProgress: 'Progress',
    regCloseConfirm: 'Close and save progress? You can resume anytime.',

    regGradeA: 'A — Excellent', regGradeB: 'B — Strong', regGradeC: 'C — Building', regGradeD: 'D — Starter',
  },
  bm: {
    tools: 'Alat Hartanah',
    phase1Tools: 'Kit sebelum tandatangan',
    phase1ToolsSub: 'Jangan tandatangan buta',
    toolScreenTile: 'Saring penyewa',       toolScreenTileSub: 'Semakan amanah',
    toolAuditTile: 'Audit perjanjian',      toolAuditTileSub: 'Imbas klausa',
    toolStampTile: 'Duti setem',            toolStampTileSub: 'SDSAS 2026',
    exportPdf: 'Muat turun PDF',            exporting: 'Menyediakan PDF…',
    stampSavedToCase: 'Disimpan ke memori kes',
    // === TOOL 1 — Payment Discipline Scan (Bloomberg-not-FICO) ===========
    screenTitleV2: 'Imbasan Disiplin Pembayaran',
    screenDescV2: 'Tunjuk 4 skrin aplikasi semasa tinjauan. Tiada muat naik, tiada penyata bank.',
    screenSubDnaFooter: 'Find.ai hanya memaparkan tingkah laku bayaran. Keputusan untuk meneruskan sewaan sepenuhnya di tangan tuan rumah.',
    screenTenantSection: 'Penyewa semasa tinjauan',
    screenTenantName: 'Nama penuh (ikut MyKad)',
    screenTenantIC: '4 digit akhir IC',
    screenTenantPhone: 'Nombor telefon',
    screenConsentTitle: 'Kebenaran (tanda semasa tinjauan)',
    screenConsentText: 'Penyewa telah memberi kebenaran lisan untuk berkongsi skrin aplikasi pembayaran ini dengan tuan rumah untuk permohonan sewaan ini sahaja. Data dipadam 12 bulan selepas sewaan tamat.',
    screenStartScan: 'Mula imbasan 4 langkah',
    screenStepElec: 'Langkah 1 · Elektrik',
    screenStepMobile: 'Langkah 2 · Pascabayar mudah alih',
    screenStepInternet: 'Langkah 3 · Internet rumah',
    screenStepWildcard: 'Langkah 4 · Satu langganan sukarela',
    screenElecApps: 'myTNB · mySESB · SEB Cares',
    screenMobileApps: 'MyMaxis · CelcomDigi · U Mobile · Yes · Yoodo',
    screenInternetApps: 'MyUnifi · MyMaxis Home · Time · Yes Home',
    screenAccountName: 'Nama pada akaun',
    screenOnTime: 'Bulan bayar tepat masa (daripada 12 bulan lepas)',
    screenTenure: 'Tempoh akaun',
    screenArrears: 'Ada tunggakan / pemutusan sekarang?',
    screenVendor: 'Aplikasi / vendor mana?',
    screenVendorHint: 'cth. Unifi, Maxis Home, Time',
    screenWildcardHint: 'Pilih satu auto-debit berulang sukarela yang penyewa ada.',
    screenWildcardCategories: {
      waterFilter: 'Penapis air (Coway / Cuckoo / lain)',
      takaful: 'Insurans / Takaful',
      streaming: 'Strim (Netflix / Spotify / Astro / iQiyi…)',
      gym: 'Keahlian gim',
      ewallet: 'Auto-isi e-dompet (TnG / GrabPay / Boost)',
      other: 'Auto-debit berulang lain',
    },
    screenTenureBuckets: {
      lt6: 'Kurang dari 6 bulan',
      sixTo12: '6–12 bulan',
      oneTo2y: '1–2 tahun',
      twoTo5y: '2–5 tahun',
      gt5y: 'Lebih 5 tahun',
    },
    screenSkip: 'Langkau (tidak berkenaan)',
    screenNext: 'Seterusnya',
    screenBackStep: 'Kembali',
    screenReview: 'Semakan',
    screenIndexLabel: 'Indeks Disiplin Pembayaran',
    screenCoverage: 'Berdasarkan {n} daripada 4 isyarat',
    screenNoVerdict: 'Ini bukan cadangan. Nombor menggambarkan tingkah laku, bukan kesesuaian.',
    screenFinish: 'Selesai imbasan',
    screenExportPdf: 'Muat Turun PDF Imbasan',
    screenSaveToCase: 'Simpan ke memori kes',
    screenSavedToCase: 'Disimpan ke memori kes',
    screenNameMismatch: 'Nama akaun berbeza dengan MyKad',
    screenNameMatch: 'Nama sepadan dengan MyKad',
    screenPartialMatch: 'Nama padanan separa',
    screenArrearsFlag: 'Tunggakan semasa pada akaun ini',
    screenYes: 'Ya', screenNo: 'Tidak',
    screenSignalElectricity: 'Elektrik',
    screenSignalMobile: 'Mudah alih',
    screenSignalInternet: 'Internet',
    screenSignalWildcard: 'Langganan sukarela',
    // =====================================================================
    stampTitle: 'Kalkulator Duti Setem', stampDesc: 'Duti setem perjanjian sewa',
    yieldTitle: 'Kalkulator Pulangan Sewa', yieldDesc: 'Adakah hartanah anda berbaloi?',
    screenTitle: 'Saringan Penyewa', screenDesc: 'Semak risiko penyewa sebelum tandatangan',
    healthTitle: 'Semakan Perjanjian', healthDesc: 'Adakah perjanjian anda melindungi anda?',
    monthlyRent: 'Sewa Bulanan (RM)', leaseDuration: 'Tempoh Sewa',
    years: ['1 tahun', '2 tahun', '3 tahun', '5 tahun'],
    stampResult: 'Duti Setem Perlu Dibayar (SDSAS 2026)', stampExempt: 'Dikecualikan — tiada duti setem',
    stampNote: 'Perjanjian tanpa setem tidak boleh digunakan di mahkamah.',
    stampWho: 'Biasanya dibayar oleh penyewa, tetapi boleh dirunding.',
    stampDeadline: 'Mesti setem dalam 30 hari selepas tandatangan. Lewat = penalti sehingga 100%.',
    stampPerUnit: 'setiap unit RM250 sewa tahunan',
    sdsasNote: 'Sistem taksiran sendiri (SDSAS) berkuat kuasa Jan 2026. Pengecualian RM2,400 dimansuhkan. Anda kira dan bayar melalui MyTax.',
    oldDuty: 'Kadar Lama (Sebelum 2026)', dutyIncrease: 'Kenaikan',
    wasExempt: 'Sewa ini sebelum ini DIKECUALIKAN (bawah RM2,400/thn). Di bawah peraturan 2026, duti setem kini dikenakan.',
    vaultTitle: 'Bukti Foto', vaultDesc: 'Lindungi diri — tangkap, kunci, siap',
    vaultAddress: 'Nama Hartanah / Kondo', vaultAddressHint: 'cth. Lakefront Residence, Cyberjaya',
    vaultUnit: 'Nombor Unit', vaultType: 'Untuk apa ini?', vaultSelectType: 'Pilih satu',
    vaultCheckIn: 'Penyewa masuk', vaultCheckOut: 'Penyewa keluar', vaultDamage: 'Rakam kerosakan', vaultGeneral: 'Lain-lain',
    vaultUpload: 'Tambah Gambar', vaultUploadHint: 'Ambil gambar atau pilih dari galeri — kami kunci setiap satu supaya tak boleh dipertikaikan',
    vaultHashing: 'Mengunci gambar anda...', vaultPhotos: 'Gambar Anda', vaultHash: 'Perlindungan',
    vaultGenerate: 'Cipta Sijil Bukti', vaultVerified: 'DIKUNCI & DILINDUNGI',
    vaultCertId: 'No. Sijil', vaultDownload: 'Muat Turun Sijil Anda',
    vaultLegalNote: 'Sijil ini membuktikan gambar anda asli dan tidak diubah. Ia diterima di mahkamah Malaysia di bawah Akta Keterangan. Simpan gambar asal — jangan edit atau tukar nama.',
    annualRent: 'Sewa Tahunan', purchasePrice: 'Harga Belian (RM)',
    monthlyExpenses: 'Perbelanjaan Bulanan (RM)', expensesHint: 'Penyelenggaraan, insurans, cukai taksiran',
    grossYield: 'Pulangan Kasar', netYield: 'Pulangan Bersih',
    annualProfit: 'Untung Tahunan', monthlyProfit: 'Untung Bulanan',
    verdict: 'Keputusan',
    verdictGood: 'Pelaburan baik — melebihi purata pasaran',
    verdictOk: 'Sederhana — pertimbangkan potensi kenaikan nilai',
    verdictWeak: 'Di bawah purata — semak harga sewa atau perbelanjaan',
    calculate: 'Kira',
    tenantSalary: 'Gaji Bulanan Penyewa (RM)', rentAmount: 'Sewa Bulanan (RM)',
    jobType: 'Jenis Pekerjaan', occupants: 'Bilangan Penghuni', bedrooms: 'Bilik Tidur',
    moveReason: 'Sebab Pindah', hasGuarantor: 'Ada Penjamin?',
    jobs: { permanent: 'Tetap', contract: 'Kontrak', selfEmployed: 'Sendiri', unemployed: 'Menganggur/Pelajar' },
    reasons: { leaseEnd: 'Sewa tamat', work: 'Dekat tempat kerja', family: 'Sebab keluarga', evicted: 'Diusir', firstTime: 'Pertama kali sewa' },
    yes: 'Ya', no: 'Tidak', checkTenant: 'Saring Penyewa',
    riskLevel: 'Tahap Risiko', riskLow: 'RENDAH', riskMed: 'SEDERHANA', riskHigh: 'TINGGI',
    redFlags: 'Amaran', greenFlags: 'Positif', recommendation: 'Cadangan',
    affordability: 'Nisbah Kemampuan',
    checkAgreement: 'Semak Perjanjian', score: 'Skor Perjanjian', missing: 'Klausa Tiada', present: 'Ada',
    strong: 'KUAT — Dilindungi dengan baik', moderate: 'SEDERHANA — Ada jurang perlu diperbaiki', weak: 'LEMAH — Jurang besar, risiko tinggi',
    clauses: [
      { id: 'latePay', q: 'Klausa denda bayaran lewat?' },
      { id: 'deposit', q: 'Jumlah deposit dinyatakan (2+1)?' },
      { id: 'maintenance', q: 'Tanggungjawab penyelenggaraan dinyatakan?' },
      { id: 'sublet', q: 'Larangan sewa kecil?' },
      { id: 'earlyTermination', q: 'Klausa penamatan awal?' },
      { id: 'inventory', q: 'Senarai semak inventori masuk/keluar?' },
      { id: 'utility', q: 'Klausa pemindahan utiliti & bil akhir?' },
      { id: 'stampDuty', q: 'Tanggungjawab duti setem dinyatakan?' },
      { id: 'renewal', q: 'Terma pembaharuan dinyatakan?' },
      { id: 'dispute', q: 'Kaedah penyelesaian pertikaian?' },
    ],
    clauseFix: {
      latePay: 'Tambah: "Caj lewat 10% setahun atas baki tertunggak selepas 14 hari"',
      deposit: 'Tambah: "Deposit keselamatan 2 bulan sewa + 0.5 bulan deposit utiliti"',
      maintenance: 'Tambah: "Penyewa bertanggungjawab atas haus & lusuh. Tuan rumah bertanggungjawab atas struktur"',
      sublet: 'Tambah: "Penyewa tidak boleh menyewa kecil tanpa kebenaran bertulis"',
      earlyTermination: 'Tambah: "Mana-mana pihak boleh menamatkan dengan notis 2 bulan bertulis"',
      inventory: 'Tambah: "Inventori terperinci dengan gambar ditandatangani kedua-dua pihak"',
      utility: 'Tambah: "Penyewa perlu tukar nama utiliti dalam 14 hari"',
      stampDuty: 'Tambah: "Duti setem ditanggung oleh Penyewa"',
      renewal: 'Tambah: "Penyewa mempunyai hak pembaharuan pertama dengan notis 2 bulan"',
      dispute: 'Tambah: "Pertikaian dirujuk kepada mediasi sebelum mahkamah"',
    },
    trustTitle: 'Pautan Kepercayaan CN-MY', trustDesc: 'Sahkan syarikat China sebelum tandatangan sewa',
    usccLabel: 'Kod USCC 18 Digit', usccHint: 'Kod Kredit Sosial Bersepadu dari lesen perniagaan',
    usccInvalid: 'USCC tidak sah — mesti 18 aksara (huruf + nombor)',
    companyName: 'Nama Syarikat (中文)', companyNameEn: 'Nama Syarikat (English)',
    paidInCapital: 'Modal Berbayar (RMB)', taxRating: 'Penarafan Kredit Cukai',
    taxRatings: { A: 'Gred A — Cemerlang', B: 'Gred B — Baik', C: 'Gred C — Sederhana', D: 'Gred D — Lemah' },
    yearsOp: 'Tahun Beroperasi', bizScope: 'Skop Perniagaan',
    bizScopes: { manufacturing: 'Pembuatan', trading: 'Perdagangan', logistics: 'Logistik', tech: 'Teknologi', other: 'Lain-lain' },
    abnormalOps: 'Dalam Senarai Operasi Tidak Normal?',
    courtRecords: 'Rekod Mahkamah/Pertikaian?',
    generateReport: 'Jana Laporan Kepercayaan',
    trustGrade: 'Gred Kepercayaan', trustScore: 'Skor Kepercayaan',
    trustA: 'GRED A — Risiko Rendah. Selamat diteruskan.',
    trustB: 'GRED B — Sederhana. Teruskan dengan penjamin + deposit tambahan.',
    trustC: 'GRED C — Risiko Tinggi. Minta jaminan bank.',
    trustD: 'GRED D — Sangat Berisiko. Tidak digalakkan.',
    riskFactors: 'Faktor Risiko', positiveFactors: 'Faktor Positif',
    trustDisclaimer: 'Laporan nasihat sahaja. Bukan jaminan kredit. Sahkan semua maklumat secara bebas.',
    downloadReport: 'Muat Turun Laporan',
    trustLookup: 'Mencari syarikat...', trustFound: 'Syarikat dijumpai dalam pangkalan data',
    trustNotFound: 'Tiada dalam pangkalan data — masukkan butiran secara manual', trustAutoFill: 'Diisi automatik dari pangkalan data',
    trustManual: 'Kemasukan Manual', trustAuto: 'Carian Auto',
    trustRetry: 'Cuba Semula', trustOffline: 'Sambungan gagal — masukkan butiran secara manual',
    trafficGreen: 'LAMPU HIJAU — Selamat diteruskan', trafficYellow: 'LAMPU KUNING — Teruskan dengan berhati-hati', trafficRed: 'LAMPU MERAH — Risiko tinggi',
    myCheckTitle: 'Semakan Syarikat MY', myCheckDesc: 'Sahkan syarikat Malaysia sebelum tandatangan sewa',
    ssmLabel: 'Nombor Syarikat SSM', ssmHint: 'Nombor pendaftaran 12 digit dari SSM',
    ssmInvalid: 'Nombor SSM tidak sah — mesti 12 digit',
    myCompanyName: 'Nama Syarikat', myCompanyType: 'Jenis Syarikat', myPaidUpCapital: 'Modal Berbayar (RM)',
    myYearsOp: 'Tahun Beroperasi', myStatus: 'Status Syarikat', myDirectors: 'Pengarah',
    myNature: 'Jenis Perniagaan', myAddress: 'Alamat Berdaftar', myCompliant: 'Pemfailan SSM Terkini',
    myTypes: { 'sdn-bhd': 'Sdn Bhd', 'bhd': 'Berhad', 'llp': 'PLT', 'partnership': 'Perkongsian', 'sole-prop': 'Milikan Tunggal' },
    myStatuses: { active: 'Aktif', dormant: 'Dorman', 'struck-off': 'Dibatalkan', 'winding-up': 'Penggulungan' },
    myGenerateReport: 'Jana Laporan Syarikat', myDownloadReport: 'Muat Turun Laporan Syarikat',
    myDisclaimer: 'Laporan nasihat sahaja. Berdasarkan data SSM. Bukan jaminan kredit. Sahkan semua maklumat secara bebas.',
    chatCardTitle: 'Soal Jawab Hartanah', chatCardDesc: 'Tanya apa-apa soalan tuan rumah, penyewa, atau pembeli',
    cnCardTitle: 'Semakan Syarikat CN', cnCardDesc: 'Sahkan syarikat China (USCC)',
    myCardTitle: 'Semakan Syarikat MY', myCardDesc: 'Sahkan syarikat Malaysia (SSM)',
    navTitle: 'Navigator Situasi', navDesc: 'Panduan langkah demi langkah untuk pertikaian',
    navPick: 'Apa situasi anda?',
    navRentDefault: 'Sewa Tertunggak', navRentDefaultDesc: 'Penyewa tak bayar sewa',
    navDeposit: 'Pertikaian Deposit', navDepositDesc: 'Deposit tak dipulangkan',
    navEviction: 'Proses Pengusiran', navEvictionDesc: 'Perlu usir penyewa secara sah',
    navTimeline: 'Garis Masa', navCost: 'Anggaran Kos', navLaw: 'Asas Undang-undang',
    navStep: 'Langkah', navAction: 'Apa perlu buat', navWarning: 'Amaran',
    navDocument: 'Templat Dokumen', navCopyDoc: 'Salin Templat',
    navBack: 'Kembali ke situasi',
    bridgeTitle: 'Boleh Buat Ini?', bridgeDesc: 'Semakan pematuhan hartanah Malaysia',
    bridgePick: 'Apa yang anda mahu buat di Malaysia?', bridgePickSub: 'Pilih matlamat anda — kami tunjukkan semua yang perlu',
    bridgeRent: 'Sewa Hartanah', bridgeBuy: 'Beli Hartanah', bridgeOperate: 'Operasi Perniagaan',
    bridgeRentHouse: 'Sewa Rumah / Kondo', bridgeRentHouseDesc: 'Sewaan kediaman sebagai warga asing',
    bridgeRentOffice: 'Sewa Pejabat / Kedai', bridgeRentOfficeDesc: 'Sewa komersial untuk perniagaan',
    bridgeRentFactory: 'Sewa Kilang / Gudang', bridgeRentFactoryDesc: 'Sewa perindustrian untuk pembuatan',
    bridgeBuyHouse: 'Beli Rumah / Kondo', bridgeBuyHouseDesc: 'Syarat pemilikan asing',
    bridgeBuyLand: 'Beli Tanah', bridgeBuyLandDesc: 'Pertanian, pembangunan, kosong',
    bridgeOpenFnb: 'Buka Restoran / F&B', bridgeOpenFnbDesc: 'Pelesenan perniagaan makanan',
    bridgeSetupFactory: 'Tubuhkan Kilang', bridgeSetupFactoryDesc: 'Operasi pembuatan',
    bridgeSpecify: 'Beritahu kami lagi', bridgeSpecifySub: 'Situasi berbeza perlukan lesen berbeza',
    bridgeActivity: 'Apa yang akan anda buat?', bridgeWhere: 'Di mana?', bridgeAgriLand: 'Adakah di atas tanah pertanian?',
    bridgeForeignWorkers: 'Akan bawa pekerja asing?', bridgeCheckBtn: 'Semak Keperluan Saya',
    bridgeYes: 'Ya', bridgeNo: 'Tidak', bridgeNotSure: 'Tidak Pasti',
    bridgeVerdictYes: 'YA — Anda boleh buat ini', bridgeVerdictMaybe: 'YA BERSYARAT', bridgeVerdictNo: 'TIDAK DIBENARKAN',
    bridgeRequired: 'WAJIB', bridgeRequiredSub: 'Mesti ada sebelum beroperasi',
    bridgeRecommended: 'DISYORKAN', bridgeRecommendedSub: 'Sangat digalakkan',
    bridgeDept: 'Jabatan', bridgeTimeline: 'Garis Masa', bridgeCost: 'Kos',
    bridgeTotalLicenses: 'Jumlah lesen diperlukan', bridgeTotalTime: 'Anggaran jumlah masa',
    bridgeTotalCost: 'Anggaran jumlah kos', bridgeDownload: 'Muat Turun Senarai Penuh',
    bridgeAskAI: 'Tanya Find.ai', bridgeBack: 'Kembali',
    bridgeCNTrap: 'Perangkap Andaian China',
    bridgeNote: 'Panduan nasihat sahaja. Keperluan mungkin berbeza mengikut pihak berkuasa tempatan.',
    bridgeTimeline2: 'Garis Masa Biasa',
    bridgeManufacturing: 'Pembuatan / Pemasangan', bridgeManufacturingDesc: 'Menghasilkan atau memasang produk',
    bridgeWarehouse: 'Gudang / Penyimpanan', bridgeWarehouseDesc: 'Menyimpan barang, hab logistik',
    bridgeChemical: 'Kimia / Berbahaya', bridgeChemicalDesc: 'Bekerja dengan bahan kimia',
    bridgeFoodProcessing: 'Pemprosesan Makanan', bridgeFoodProcessingDesc: 'Pengilangan atau pembungkusan makanan',
    // === PATH D — Pra-Pendaftaran Penyewa ("Daftar sekali, sewa mana-mana") =====
    regTitle: 'Daftar sekali, sewa mana-mana',
    regDesc: 'Bina profil amanah yang tuan rumah akan dapat lihat dalam 1 saat.',
    regStepOf: 'Langkah {n} daripada 5',
    regStartCTA: 'Mula buat profil',
    regAlreadyHave: 'Saya ada profil',
    regResume: 'Sambung pendaftaran',

    regS1Title: 'Sahkan telefon anda',
    regS1Sub: 'Mana-mana nombor mobile MY — Celcom, Digi, Maxis, Umobile, Yoodo.',
    regS1PhoneLabel: 'Nombor telefon',
    regS1PhonePlaceholder: '+60 12-345 6789',
    regS1SendOTP: 'Hantar kod 6-digit',
    regS1SendingOTP: 'Menghantar…',
    regS1OTPLabel: 'Masukkan kod yang kami hantar',
    regS1OTPPlaceholder: 'Kod 6-digit',
    regS1Verify: 'Sahkan',
    regS1Verified: 'Telefon disahkan',
    regS1PhoneInvalid: 'Masukkan nombor mobile MY yang sah',
    regS1OTPInvalid: 'Kod tidak padan. Cubaan berbaki: {n}.',
    regS1OTPExpired: 'Kod tamat tempoh. Minta yang baru.',
    regS1Resend: 'Hantar semula',
    regS1MockNote: 'Mod demo — kod ditunjukkan dalam konsol pelayar. Versi sebenar guna SMS.',

    regS2Title: 'Identiti anda',
    regS2Sub: 'Hanya untuk padankan nama anda dengan akaun utiliti. IC di-hash, tidak disimpan dalam bentuk mentah.',
    regS2NameLabel: 'Nama penuh (ikut MyKad)',
    regS2NamePlaceholder: 'cth. Siti Aminah Binti Hassan',
    regS2ICLabel: 'Nombor IC (12 digit)',
    regS2ICPlaceholder: '950203-08-1234',
    regS2ICInvalid: 'Format IC mesti 12 digit (YYMMDD-PB-XXXG)',
    regS2SelfieLabel: 'Swafoto langsung (pilihan)',
    regS2SelfieHint: 'Menambah lapisan pengesahan identiti — langkau untuk buat kemudian.',
    regS2SelfieAdd: 'Ambil swafoto',
    regS2SelfieCaptured: 'Swafoto diambil',

    regS3Title: 'Akaun elektrik TNB',
    regS3Sub: 'Taip nombor akaun TNB, kemudian muat naik bil TNB terkini. Kami padankan nombor dengan bil.',
    regS3AccountLabel: 'Nombor akaun TNB (12 digit)',
    regS3AccountPlaceholder: 'cth. 2200 1234 5678',
    regS3BillUpload: 'Muat naik bil TNB terkini (PDF atau foto)',
    regS3BillUploaded: 'Bil diterima — {name}',
    regS3BillAmountLabel: 'Jumlah bil terakhir (RM)',
    regS3BillDateLabel: 'Tarikh bil',
    regS3PaidOnTime: 'Dibayar pada atau sebelum tarikh akhir?',
    regS3Verify: 'Sahkan akaun',
    regS3Verified: 'Akaun TNB disahkan',
    regS3Skip: 'Langkau — tambah kemudian',

    regS4Title: 'Internet rumah Unifi / Maxis Home',
    regS4Sub: 'Corak sama — nombor akaun dan satu bil terkini.',
    regS4ProviderLabel: 'Pembekal',
    regS4ProviderUnifi: 'Unifi',
    regS4ProviderMaxisHome: 'Maxis Home',
    regS4ProviderTime: 'Time',
    regS4ProviderYesHome: 'Yes Home',
    regS4AccountLabel: 'Nombor akaun',
    regS4AccountPlaceholder: 'cth. ABC12345',
    regS4BillUpload: 'Muat naik bil terkini (PDF atau foto)',
    regS4Verify: 'Sahkan akaun',
    regS4Verified: 'Akaun internet disahkan',

    regS5Title: 'Keizinan & siapkan',
    regS5Sub: 'Profil anda hidup sebaik sahaja anda tekan Cipta. Anda kawal setiap perkongsian akan datang.',
    regS5Consent1: 'Saya benarkan Find.ai menyimpan profil ini untuk tujuan amanah tenansi di bawah PDPA 2010.',
    regS5Consent2: 'Saya benarkan pembaharuan automatik bulanan melalui bil utiliti yang dimajukan (pilihan).',
    regS5Consent2Sub: 'Menjaga sejarah pembayaran anda sentiasa terkini supaya tuan rumah lihat data terbaru.',
    regS5PDPARights: 'Anda boleh lihat, eksport, atau padam profil pada bila-bila masa (PDPA s.30-34).',
    regS5Create: 'Cipta profil amanah saya',
    regS5Creating: 'Mencipta…',

    regDoneTitle: 'Profil anda aktif',
    regDoneSub: 'Kongsi pautan ini dengan mana-mana tuan rumah — mereka nampak gred anda serta-merta.',
    regDoneGrade: 'Gred permulaan anda',
    regDoneGradeNote: 'Gred bertambah baik apabila sejarah pembayaran terkumpul. Bulan ke-6 biasanya A.',
    regDoneLink: 'Pautan kongsi anda',
    regDoneCopy: 'Salin pautan',
    regDoneCopied: 'Disalin',
    regDoneOpenWA: 'Kongsi via WhatsApp',
    regDoneNext: 'Siap',
    regDoneWAMsg: 'Hi — ini profil penyewa Find.ai saya: {url}\n\n1 tekan untuk lihat sejarah pembayaran disahkan. Boleh tarik balik bila-bila masa.',

    regBack: 'Kembali',
    regNext: 'Seterusnya',
    regSkipStep: 'Langkau langkah',
    regProgress: 'Kemajuan',
    regCloseConfirm: 'Tutup dan simpan kemajuan? Boleh sambung bila-bila.',

    regGradeA: 'A — Cemerlang', regGradeB: 'B — Kukuh', regGradeC: 'C — Membina', regGradeD: 'D — Permulaan',
  },
  zh: {
    tools: '房产工具',
    phase1Tools: '签约前工具箱',
    phase1ToolsSub: '签约前先查清',
    toolScreenTile: '筛查租客',             toolScreenTileSub: '信用检查',
    toolAuditTile: '审查协议',              toolAuditTileSub: '条款扫描',
    toolStampTile: '印花税',                toolStampTileSub: 'SDSAS 2026',
    exportPdf: '导出 PDF',                  exporting: '正在生成 PDF…',
    stampSavedToCase: '已存入案件记忆',
    // === TOOL 1 — Payment Discipline Scan (Bloomberg-not-FICO) ===========
    screenTitleV2: '付款纪律扫描',
    screenDescV2: '看房时展示4个应用界面。无需上传，无需银行对账单。',
    screenSubDnaFooter: 'Find.ai 仅呈现付款行为。是否签约完全由房东自行决定。',
    screenTenantSection: '看房当天的租客',
    screenTenantName: '全名（按身份证）',
    screenTenantIC: '身份证后4位',
    screenTenantPhone: '手机号码',
    screenConsentTitle: '授权（看房时勾选）',
    screenConsentText: '租客已口头同意在此次租赁申请中向房东出示这些付款应用界面。数据将在租赁结束12个月后删除。',
    screenStartScan: '开始4步扫描',
    screenStepElec: '步骤1 · 电费',
    screenStepMobile: '步骤2 · 手机后付',
    screenStepInternet: '步骤3 · 家庭宽带',
    screenStepWildcard: '步骤4 · 一项自愿订阅',
    screenElecApps: 'myTNB · mySESB · SEB Cares',
    screenMobileApps: 'MyMaxis · CelcomDigi · U Mobile · Yes · Yoodo',
    screenInternetApps: 'MyUnifi · MyMaxis Home · Time · Yes Home',
    screenAccountName: '账户姓名',
    screenOnTime: '过去12个月中按时支付的月份',
    screenTenure: '账户使用时长',
    screenArrears: '当前是否有欠款/断缴？',
    screenVendor: '哪个应用/服务商？',
    screenVendorHint: '例：Unifi、Maxis Home、Time',
    screenWildcardHint: '选择租客的一项自愿循环自动扣款。',
    screenWildcardCategories: {
      waterFilter: '净水器（Coway / Cuckoo / 其他）',
      takaful: '保险 / Takaful',
      streaming: '流媒体（Netflix / Spotify / Astro / 爱奇艺…）',
      gym: '健身房会员',
      ewallet: '电子钱包自动充值（TnG / GrabPay / Boost）',
      other: '其他循环自动扣款',
    },
    screenTenureBuckets: {
      lt6: '不到6个月',
      sixTo12: '6–12个月',
      oneTo2y: '1–2年',
      twoTo5y: '2–5年',
      gt5y: '5年以上',
    },
    screenSkip: '跳过（不适用）',
    screenNext: '下一步',
    screenBackStep: '返回',
    screenReview: '回顾',
    screenIndexLabel: '付款纪律指数',
    screenCoverage: '基于4项信号中的{n}项',
    screenNoVerdict: '这不是推荐建议。数字描述行为，不代表适合度。',
    screenFinish: '完成扫描',
    screenExportPdf: '导出扫描PDF',
    screenSaveToCase: '存入案件记忆',
    screenSavedToCase: '已存入案件记忆',
    screenNameMismatch: '账户姓名与身份证不一致',
    screenNameMatch: '姓名与身份证一致',
    screenPartialMatch: '姓名部分匹配',
    screenArrearsFlag: '此账户当前有欠款',
    screenYes: '是', screenNo: '否',
    screenSignalElectricity: '电费',
    screenSignalMobile: '手机',
    screenSignalInternet: '宽带',
    screenSignalWildcard: '自愿订阅',
    // =====================================================================
    stampTitle: '印花税计算器', stampDesc: '租约印花税',
    yieldTitle: '租金回报计算器', yieldDesc: '您的房产值得投资吗？',
    screenTitle: '租客筛查', screenDesc: '签约前检查租客风险',
    healthTitle: '协议健康检查', healthDesc: '您的协议是否保护您？',
    monthlyRent: '月租金 (RM)', leaseDuration: '租约期限',
    years: ['1年', '2年', '3年', '5年'],
    stampResult: '应付印花税 (SDSAS 2026)', stampExempt: '豁免 — 无需缴纳印花税',
    stampNote: '未盖章的协议不能在法庭上作为证据。',
    stampWho: '通常由租客支付，但可协商。',
    stampDeadline: '签约后30天内必须盖章。逾期 = 最高100%罚款。',
    stampPerUnit: '每RM250年租单位',
    sdsasNote: '自我评估系统（SDSAS）2026年1月生效。RM2,400豁免已取消。您需通过MyTax自行计算和缴付。',
    oldDuty: '旧规则（2026年前）', dutyIncrease: '涨幅',
    wasExempt: '此租金之前获豁免（低于RM2,400/年）。2026年新规下，现需缴纳印花税。',
    vaultTitle: '照片证明', vaultDesc: '保护自己 — 拍照、锁定、完成',
    vaultAddress: '房产/公寓名称', vaultAddressHint: '例：Lakefront Residence, Cyberjaya',
    vaultUnit: '单位号', vaultType: '这是用于什么？', vaultSelectType: '选择一个',
    vaultCheckIn: '租客入住', vaultCheckOut: '租客退房', vaultDamage: '记录损坏', vaultGeneral: '其他',
    vaultUpload: '添加照片', vaultUploadHint: '拍照或从相册选择 — 我们会锁定每张照片，确保无法被争议',
    vaultHashing: '正在锁定您的照片...', vaultPhotos: '您的照片', vaultHash: '保护方式',
    vaultGenerate: '创建证明证书', vaultVerified: '已锁定和保护',
    vaultCertId: '证书编号', vaultDownload: '下载您的证书',
    vaultLegalNote: '本证书证明您的照片为原始照片且未被篡改。它依据马来西亚证据法在法庭上被接受。请妥善保管原始照片 — 不要编辑或重命名。',
    annualRent: '年租金', purchasePrice: '购买价格 (RM)',
    monthlyExpenses: '每月支出 (RM)', expensesHint: '管理费、保险、门牌税、地税',
    grossYield: '毛回报率', netYield: '净回报率',
    annualProfit: '年净利润', monthlyProfit: '月净利润',
    verdict: '评估',
    verdictGood: '好投资 — 高于市场平均',
    verdictOk: '一般 — 考虑升值潜力',
    verdictWeak: '低于平均 — 检查租金或支出',
    calculate: '计算',
    tenantSalary: '租客月薪 (RM)', rentAmount: '月租金 (RM)',
    jobType: '就业类型', occupants: '住户人数', bedrooms: '卧室数量',
    moveReason: '搬迁原因', hasGuarantor: '有担保人？',
    jobs: { permanent: '全职', contract: '合同', selfEmployed: '自雇', unemployed: '无业/学生' },
    reasons: { leaseEnd: '租约到期', work: '靠近工作', family: '家庭原因', evicted: '被驱逐', firstTime: '首次租房' },
    yes: '是', no: '否', checkTenant: '筛查租客',
    riskLevel: '风险等级', riskLow: '低风险', riskMed: '中等风险', riskHigh: '高风险',
    redFlags: '警告', greenFlags: '优点', recommendation: '建议',
    affordability: '负担能力比',
    checkAgreement: '检查协议', score: '协议评分', missing: '缺失条款', present: '已有',
    strong: '强 — 保护良好', moderate: '中等 — 需要修补', weak: '弱 — 重大漏洞，高风险',
    clauses: [
      { id: 'latePay', q: '逾期付款罚款条款？' },
      { id: 'deposit', q: '押金金额明确（2+1）？' },
      { id: 'maintenance', q: '维修责任明确？' },
      { id: 'sublet', q: '禁止转租条款？' },
      { id: 'earlyTermination', q: '提前终止条款？' },
      { id: 'inventory', q: '入住/退房清单？' },
      { id: 'utility', q: '水电转名及最终账单条款？' },
      { id: 'stampDuty', q: '印花税责任明确？' },
      { id: 'renewal', q: '续约条款？' },
      { id: 'dispute', q: '争议解决方式？' },
    ],
    clauseFix: {
      latePay: '添加："逾期14天后按年利率10%收取滞纳金"',
      deposit: '添加："押金为2个月租金 + 0.5个月水电押金"',
      maintenance: '添加："租客负责日常损耗，房东负责结构性维修"',
      sublet: '添加："未经书面同意，租客不得转租"',
      earlyTermination: '添加："任何一方可提前2个月书面通知终止"',
      inventory: '添加："双方签署附照片的详细清单"',
      utility: '添加："租客须在14天内将水电转至本人名下"',
      stampDuty: '添加："印花税由租客承担"',
      renewal: '添加："租客有优先续约权，需提前2个月通知"',
      dispute: '添加："争议先提交调解再诉诸法院"',
    },
    trustTitle: '中马信任链接', trustDesc: '签约前验证中国公司资质',
    usccLabel: '18位统一社会信用代码', usccHint: '营业执照上的统一社会信用代码',
    usccInvalid: '无效USCC — 必须为18位字符（字母+数字）',
    companyName: '公司名称（中文）', companyNameEn: '公司名称（英文）',
    paidInCapital: '实缴资本（人民币）', taxRating: '纳税信用等级',
    taxRatings: { A: 'A级 — 优秀', B: 'B级 — 良好', C: 'C级 — 一般', D: 'D级 — 较差' },
    yearsOp: '运营年限', bizScope: '经营范围',
    bizScopes: { manufacturing: '制造业', trading: '贸易', logistics: '物流', tech: '科技', other: '其他' },
    abnormalOps: '是否在经营异常名录？',
    courtRecords: '是否有法院/法律纠纷？',
    generateReport: '生成信任报告',
    trustGrade: '信任等级', trustScore: '信任分数',
    trustA: 'A级 — 低风险。可安全签约。',
    trustB: 'B级 — 中等风险。建议增加担保人和额外押金。',
    trustC: 'C级 — 较高风险。要求银行担保。',
    trustD: 'D级 — 高风险。不建议签约。',
    riskFactors: '风险因素', positiveFactors: '积极因素',
    trustDisclaimer: '仅供参考。非信用担保。签约前请独立核实所有信息。',
    downloadReport: '下载信任报告',
    trustLookup: '正在查询公司...', trustFound: '已在数据库中找到公司',
    trustNotFound: '未在数据库中找到 — 请手动输入信息', trustAutoFill: '已从数据库自动填充',
    trustManual: '手动输入', trustAuto: '自动查询',
    trustRetry: '重试', trustOffline: '连接失败 — 请手动输入信息',
    trafficGreen: '绿灯 — 可安全签约', trafficYellow: '黄灯 — 需谨慎行事', trafficRed: '红灯 — 高风险',
    myCheckTitle: '马来西亚公司查询', myCheckDesc: '签约前验证马来西亚公司资质',
    ssmLabel: 'SSM公司编号', ssmHint: 'SSM 12位注册号码',
    ssmInvalid: 'SSM编号无效 — 必须为12位数字',
    myCompanyName: '公司名称', myCompanyType: '公司类型', myPaidUpCapital: '实缴资本 (RM)',
    myYearsOp: '运营年数', myStatus: '公司状态', myDirectors: '董事',
    myNature: '业务性质', myAddress: '注册地址', myCompliant: 'SSM备案最新',
    myTypes: { 'sdn-bhd': '私人有限公司', 'bhd': '上市公司', 'llp': '有限责任合伙', 'partnership': '合伙企业', 'sole-prop': '独资企业' },
    myStatuses: { active: '活跃', dormant: '休眠', 'struck-off': '已注销', 'winding-up': '清算中' },
    myGenerateReport: '生成公司报告', myDownloadReport: '下载公司报告',
    myDisclaimer: '仅供参考。基于SSM数据。非信用担保。签约前请独立核实所有信息。',
    chatCardTitle: '房产问答', chatCardDesc: '房东、租客或买家的任何问题',
    cnCardTitle: '中国公司查询', cnCardDesc: '验证中国公司（统一社会信用代码）',
    myCardTitle: '马来西亚公司查询', myCardDesc: '验证马来西亚公司（SSM）',
    navTitle: '情况导航', navDesc: '房产纠纷分步指南',
    navPick: '您面临什么情况？',
    navRentDefault: '租金拖欠', navRentDefaultDesc: '租客未缴租金',
    navDeposit: '押金纠纷', navDepositDesc: '押金未退还或不合理扣除',
    navEviction: '驱逐流程', navEvictionDesc: '需要合法驱逐租客',
    navTimeline: '时间线', navCost: '预估费用', navLaw: '法律依据',
    navStep: '步骤', navAction: '该怎么做', navWarning: '警告',
    navDocument: '文件模板', navCopyDoc: '复制模板',
    navBack: '返回情况列表',
    bridgeTitle: '马来西亚办事攻略', bridgeDesc: '租房·买房·开业 — 一站式合规查询',
    bridgePick: '您想在马来西亚做什么？', bridgePickSub: '选择您的目标 — 我们会展示您需要的一切',
    bridgeRent: '租赁房产', bridgeBuy: '购买房产', bridgeOperate: '经营业务',
    bridgeRentHouse: '租住宅/公寓', bridgeRentHouseDesc: '外国人住宅租赁',
    bridgeRentOffice: '租办公室/店铺', bridgeRentOfficeDesc: '商业租赁',
    bridgeRentFactory: '租工厂/仓库', bridgeRentFactoryDesc: '工业租赁用于制造',
    bridgeBuyHouse: '买住宅/公寓', bridgeBuyHouseDesc: '外国人购房要求',
    bridgeBuyLand: '买土地', bridgeBuyLandDesc: '农业、开发、空地',
    bridgeOpenFnb: '开餐厅/餐饮', bridgeOpenFnbDesc: '食品经营许可',
    bridgeSetupFactory: '建厂', bridgeSetupFactoryDesc: '制造业运营',
    bridgeSpecify: '告诉我们更多', bridgeSpecifySub: '不同情况需要不同许可证',
    bridgeActivity: '您要做什么？', bridgeWhere: '在哪里？', bridgeAgriLand: '是否在农业用地上？',
    bridgeForeignWorkers: '是否带外劳？', bridgeCheckBtn: '检查我的要求',
    bridgeYes: '是', bridgeNo: '否', bridgeNotSure: '不确定',
    bridgeVerdictYes: '可以 — 您能做这个', bridgeVerdictMaybe: '有条件可以', bridgeVerdictNo: '不允许',
    bridgeRequired: '必需', bridgeRequiredSub: '运营前必须具备',
    bridgeRecommended: '建议', bridgeRecommendedSub: '强烈建议',
    bridgeDept: '部门', bridgeTimeline: '时间线', bridgeCost: '费用',
    bridgeTotalLicenses: '所需许可证总数', bridgeTotalTime: '预计总时间',
    bridgeTotalCost: '预计总费用', bridgeDownload: '下载完整清单',
    bridgeAskAI: '咨询Find.ai', bridgeBack: '返回',
    bridgeCNTrap: '中国思维陷阱',
    bridgeNote: '仅供参考。要求可能因当地主管部门而异。请咨询持牌顾问。',
    bridgeTimeline2: '典型时间线',
    bridgeManufacturing: '制造/组装', bridgeManufacturingDesc: '生产或组装产品',
    bridgeWarehouse: '仓储', bridgeWarehouseDesc: '存储货物、物流中心',
    bridgeChemical: '化学/危险品', bridgeChemicalDesc: '处理化学品',
    bridgeFoodProcessing: '食品加工', bridgeFoodProcessingDesc: '食品制造或包装',
    // === PATH D — 租客预注册（"注册一次，处处可租"）=====
    regTitle: '注册一次，处处可租',
    regDesc: '建立信任档案 — 未来每位房东 1 秒即可查看。',
    regStepOf: '第 {n} 步 / 共 5 步',
    regStartCTA: '开始建立档案',
    regAlreadyHave: '我已有档案',
    regResume: '继续注册',

    regS1Title: '验证您的手机',
    regS1Sub: '任何马来西亚手机号 — Celcom、Digi、Maxis、Umobile、Yoodo 均可。',
    regS1PhoneLabel: '手机号',
    regS1PhonePlaceholder: '+60 12-345 6789',
    regS1SendOTP: '发送 6 位验证码',
    regS1SendingOTP: '发送中…',
    regS1OTPLabel: '输入收到的验证码',
    regS1OTPPlaceholder: '6 位验证码',
    regS1Verify: '验证',
    regS1Verified: '手机已验证',
    regS1PhoneInvalid: '请输入有效的马来西亚手机号',
    regS1OTPInvalid: '验证码不正确。剩余 {n} 次尝试。',
    regS1OTPExpired: '验证码已过期。请重新获取。',
    regS1Resend: '重新发送',
    regS1MockNote: '演示模式 — 验证码显示在浏览器控制台。正式版使用 SMS。',

    regS2Title: '您的身份',
    regS2Sub: '仅用于将您的姓名与公用事业账户匹配。IC 经哈希处理，不以明文存储。',
    regS2NameLabel: '全名（依 MyKad）',
    regS2NamePlaceholder: '例如 Siti Aminah Binti Hassan',
    regS2ICLabel: 'IC 号码（12 位）',
    regS2ICPlaceholder: '950203-08-1234',
    regS2ICInvalid: 'IC 格式须为 12 位数字 (YYMMDD-PB-XXXG)',
    regS2SelfieLabel: '现场自拍（可选）',
    regS2SelfieHint: '增加一层身份确认 — 可跳过以后再加。',
    regS2SelfieAdd: '拍摄自拍',
    regS2SelfieCaptured: '自拍已拍摄',

    regS3Title: 'TNB 电力账户',
    regS3Sub: '输入您的 TNB 账户号码，然后上传最近的 TNB 账单 PDF。我们会比对号码与账单。',
    regS3AccountLabel: 'TNB 账户号码（12 位）',
    regS3AccountPlaceholder: '例如 2200 1234 5678',
    regS3BillUpload: '上传最近的 TNB 账单（PDF 或照片）',
    regS3BillUploaded: '账单已接收 — {name}',
    regS3BillAmountLabel: '最近账单金额（RM）',
    regS3BillDateLabel: '账单日期',
    regS3PaidOnTime: '是否按时支付？',
    regS3Verify: '确认账户',
    regS3Verified: 'TNB 账户已验证',
    regS3Skip: '跳过 — 稍后添加',

    regS4Title: 'Unifi / Maxis Home 家庭宽带',
    regS4Sub: '模式相同 — 账户号码加一份最近账单。',
    regS4ProviderLabel: '供应商',
    regS4ProviderUnifi: 'Unifi',
    regS4ProviderMaxisHome: 'Maxis Home',
    regS4ProviderTime: 'Time',
    regS4ProviderYesHome: 'Yes Home',
    regS4AccountLabel: '账户号码',
    regS4AccountPlaceholder: '例如 ABC12345',
    regS4BillUpload: '上传最近账单（PDF 或照片）',
    regS4Verify: '确认账户',
    regS4Verified: '宽带账户已验证',

    regS5Title: '同意 & 完成',
    regS5Sub: '点击"创建"后档案即时生效。每次分享您都拥有完全控制权。',
    regS5Consent1: '我授权 Find.ai 在 PDPA 2010 框架下储存此档案用于租赁信任评估。',
    regS5Consent2: '我授权通过转发的公用事业账单进行月度自动刷新（可选）。',
    regS5Consent2Sub: '保持您的付款记录最新 — 房东随时看到最新数据。',
    regS5PDPARights: '您可随时查看、导出或删除您的档案（PDPA 第 30-34 条）。',
    regS5Create: '创建我的信任档案',
    regS5Creating: '创建中…',

    regDoneTitle: '您的档案已启用',
    regDoneSub: '将此链接发给任何房东 — 他们即刻看到您的评级。',
    regDoneGrade: '您的初始评级',
    regDoneGradeNote: '随着付款记录累积，评级会提升。第 6 个月通常可达 A。',
    regDoneLink: '您的分享链接',
    regDoneCopy: '复制链接',
    regDoneCopied: '已复制',
    regDoneOpenWA: '通过 WhatsApp 分享',
    regDoneNext: '完成',
    regDoneWAMsg: '您好 — 这是我的 Find.ai 租客档案：{url}\n\n1 次点击即可查看经验证的付款记录。可随时撤销授权。',

    regBack: '返回',
    regNext: '下一步',
    regSkipStep: '跳过此步',
    regProgress: '进度',
    regCloseConfirm: '关闭并保存进度？随时可继续。',

    regGradeA: 'A — 优秀', regGradeB: 'B — 稳健', regGradeC: 'C — 建立中', regGradeD: 'D — 起步',
  },
};
