// ===== UI LABELS — EN / BM / ZH =====
// Split from calculators.js for maintainability

export const L = {
  en: {
    tools: 'Property Tools',
    stampTitle: 'Stamp Duty Calculator', stampDesc: 'Tenancy agreement stamp duty',
    yieldTitle: 'Rental Yield Calculator', yieldDesc: 'Is your property worth it?',
    screenTitle: 'Tenant Screening', screenDesc: 'Check tenant risk before signing',
    healthTitle: 'Agreement Health Check', healthDesc: 'Is your agreement protecting you?',
    monthlyRent: 'Monthly Rent (RM)', leaseDuration: 'Lease Duration',
    years: ['1 year', '2 years', '3 years', '5 years'],
    stampResult: 'Stamp Duty Payable (SDSAS 2026)', stampExempt: 'Exempt — no stamp duty required',
    stampNote: 'Unstamped agreements cannot be used as evidence in court.',
    stampWho: 'Usually paid by tenant, but negotiable.',
    stampDeadline: 'Must stamp within 30 days of signing. Late = penalty up to 100%.',
    stampPerUnit: 'per RM250 unit of annual rent',
    sdsasNote: 'Self-assessment system (SDSAS) effective Jan 2026. RM2,400 exemption removed. You calculate and pay via MyTax.',
    oldDuty: 'Old Rules (Pre-2026)', dutyIncrease: 'Increase',
    wasExempt: 'This rental was previously EXEMPT (under RM2,400/yr). Under 2026 rules, stamp duty now applies.',
    vaultTitle: 'Photo Proof', vaultDesc: 'Protect yourself — snap, lock, done',
    vaultAddress: 'Property / Condo Name', vaultAddressHint: 'e.g. Lakefront Residence, Cyberjaya',
    vaultUnit: 'Unit Number', vaultType: 'What is this for?', vaultSelectType: 'Select one',
    vaultCheckIn: 'Tenant moving in', vaultCheckOut: 'Tenant moving out', vaultDamage: 'Recording damage', vaultGeneral: 'Other',
    vaultUpload: 'Add Photos', vaultUploadHint: 'Take photos or choose from gallery — we lock each one so it can\'t be disputed',
    vaultHashing: 'Locking your photos...', vaultPhotos: 'Your Photos', vaultHash: 'Protection',
    vaultGenerate: 'Create Proof Certificate', vaultVerified: 'LOCKED & PROTECTED',
    vaultCertId: 'Certificate No.', vaultDownload: 'Download Your Certificate',
    vaultLegalNote: 'This certificate proves your photos are original and untampered. It\'s accepted in Malaysian courts under the Evidence Act. Keep your original photos safe — don\'t edit or rename them.',
    annualRent: 'Annual Rent', purchasePrice: 'Purchase Price (RM)',
    monthlyExpenses: 'Monthly Expenses (RM)', expensesHint: 'Maintenance, insurance, assessment, quit rent',
    grossYield: 'Gross Yield', netYield: 'Net Yield',
    annualProfit: 'Annual Net Profit', monthlyProfit: 'Monthly Net Profit',
    verdict: 'Verdict',
    verdictGood: 'Good investment — above market average',
    verdictOk: 'Average — consider if appreciation potential exists',
    verdictWeak: 'Below average — review your rental pricing or expenses',
    calculate: 'Calculate',
    tenantSalary: 'Tenant Monthly Salary (RM)', rentAmount: 'Your Monthly Rent (RM)',
    jobType: 'Employment Type', occupants: 'Number of Occupants', bedrooms: 'Bedrooms in Unit',
    moveReason: 'Reason for Moving', hasGuarantor: 'Has Guarantor?',
    jobs: { permanent: 'Permanent', contract: 'Contract', selfEmployed: 'Self-Employed', unemployed: 'Unemployed/Student' },
    reasons: { leaseEnd: 'Lease ended', work: 'Closer to work', family: 'Family reasons', evicted: 'Evicted / Asked to leave', firstTime: 'First time renting' },
    yes: 'Yes', no: 'No', checkTenant: 'Screen Tenant',
    riskLevel: 'Risk Level', riskLow: 'LOW RISK', riskMed: 'MEDIUM RISK', riskHigh: 'HIGH RISK',
    redFlags: 'Red Flags', greenFlags: 'Green Flags', recommendation: 'Recommendation',
    affordability: 'Affordability Ratio',
    checkAgreement: 'Check Agreement', score: 'Agreement Score', missing: 'Missing Clauses', present: 'Present',
    strong: 'STRONG — Well protected', moderate: 'MODERATE — Some gaps to fix', weak: 'WEAK — Major gaps, high risk',
    clauses: [
      { id: 'latePay', q: 'Late payment penalty clause?' },
      { id: 'deposit', q: 'Security deposit amount specified (2+1)?' },
      { id: 'maintenance', q: 'Maintenance responsibility defined?' },
      { id: 'sublet', q: 'Subletting prohibition included?' },
      { id: 'earlyTermination', q: 'Early termination clause with notice period?' },
      { id: 'inventory', q: 'Check-in/check-out inventory checklist?' },
      { id: 'utility', q: 'Utility transfer & final bill clause?' },
      { id: 'stampDuty', q: 'Stamp duty responsibility stated?' },
      { id: 'renewal', q: 'Renewal terms defined?' },
      { id: 'dispute', q: 'Dispute resolution method stated?' },
    ],
    clauseFix: {
      latePay: 'Add: "Late payment charge of 10% p.a. on outstanding sum after 14 days"',
      deposit: 'Add: "Security deposit of 2 months rent + 0.5 month utility deposit"',
      maintenance: 'Add: "Tenant responsible for wear & tear items. Landlord responsible for structural & major systems"',
      sublet: 'Add: "Tenant shall not sublet, assign or part with possession without written consent"',
      earlyTermination: 'Add: "Either party may terminate with 2 months written notice + forfeiture of deposit"',
      inventory: 'Add: "Detailed inventory with photos to be signed by both parties at check-in and check-out"',
      utility: 'Add: "Tenant to transfer utilities to own name within 14 days. Final bills to be settled before deposit refund"',
      stampDuty: 'Add: "Stamp duty on this agreement shall be borne by the Tenant"',
      renewal: 'Add: "Tenant has first right of renewal with 2 months notice before expiry at revised terms"',
      dispute: 'Add: "Disputes to be referred to mediation before court proceedings"',
    },
    trustTitle: 'CN-MY Trust Link', trustDesc: 'Verify Chinese company before signing lease',
    usccLabel: '18-Digit USCC Code', usccHint: 'Unified Social Credit Code from business license',
    usccInvalid: 'Invalid USCC — must be 18 characters (letters + numbers)',
    companyName: 'Company Name (Chinese)', companyNameEn: 'Company Name (English)',
    paidInCapital: 'Paid-in Capital (RMB)', taxRating: 'Tax Credit Rating',
    taxRatings: { A: 'Grade A — Excellent', B: 'Grade B — Good', C: 'Grade C — Fair', D: 'Grade D — Poor' },
    yearsOp: 'Years in Operation', bizScope: 'Business Scope',
    bizScopes: { manufacturing: 'Manufacturing', trading: 'Trading', logistics: 'Logistics', tech: 'Technology', other: 'Other' },
    abnormalOps: 'On Abnormal Operations List?',
    courtRecords: 'Court/Legal Disputes?',
    generateReport: 'Generate Trust Report',
    trustGrade: 'Trust Grade', trustScore: 'Trust Score',
    trustA: 'GRADE A — Low Risk. Safe to proceed with standard terms.',
    trustB: 'GRADE B — Moderate. Proceed with additional safeguards (guarantor + extra deposit).',
    trustC: 'GRADE C — Elevated Risk. Require bank guarantee or parent company guarantee.',
    trustD: 'GRADE D — High Risk. Not recommended. If proceeding, require full prepayment.',
    riskFactors: 'Risk Factors', positiveFactors: 'Positive Factors',
    trustDisclaimer: 'Advisory report only. Not a credit guarantee. Verify all information independently before signing any agreement.',
    downloadReport: 'Download Trust Report',
    trustLookup: 'Looking up company...', trustFound: 'Company found in database',
    trustNotFound: 'Not in database — enter details manually', trustAutoFill: 'Auto-filled from database',
    trustManual: 'Manual Entry', trustAuto: 'Auto Lookup',
    trustRetry: 'Retry', trustOffline: 'Connection failed — enter details manually',
    trafficGreen: 'GREEN LIGHT — Safe to proceed', trafficYellow: 'YELLOW LIGHT — Proceed with caution', trafficRed: 'RED LIGHT — High risk',
    navTitle: 'Situation Navigator', navDesc: 'Step-by-step guide for property disputes',
    navPick: 'What situation are you facing?',
    navRentDefault: 'Rent Default', navRentDefaultDesc: 'Tenant hasn\'t paid rent',
    navDeposit: 'Deposit Dispute', navDepositDesc: 'Deposit not returned or unfair deductions',
    navEviction: 'Eviction Process', navEvictionDesc: 'Need to remove tenant legally',
    navTimeline: 'Timeline', navCost: 'Estimated Cost', navLaw: 'Legal Basis',
    navStep: 'Step', navAction: 'What to do', navWarning: 'Warning',
    navDocument: 'Document Template', navCopyDoc: 'Copy Template',
    navBack: 'Back to situations',
    bridgeTitle: 'Can I Do This?', bridgeDesc: 'Malaysia property compliance checker',
    bridgePick: 'What do you want to do in Malaysia?', bridgePickSub: 'Select your goal — we\'ll show everything you need',
    bridgeRent: 'Rent Property', bridgeBuy: 'Buy Property', bridgeOperate: 'Operate Business',
    bridgeRentHouse: 'Rent a House / Condo', bridgeRentHouseDesc: 'Residential tenancy as foreigner',
    bridgeRentOffice: 'Rent an Office / Shop', bridgeRentOfficeDesc: 'Commercial lease for business',
    bridgeRentFactory: 'Rent a Factory / Warehouse', bridgeRentFactoryDesc: 'Industrial lease for manufacturing',
    bridgeBuyHouse: 'Buy a House / Condo', bridgeBuyHouseDesc: 'Foreign ownership requirements',
    bridgeBuyLand: 'Buy Land', bridgeBuyLandDesc: 'Agricultural, development, vacant',
    bridgeOpenFnb: 'Open a Restaurant / F&B', bridgeOpenFnbDesc: 'Food business licensing',
    bridgeSetupFactory: 'Set Up a Factory', bridgeSetupFactoryDesc: 'Manufacturing operations',
    bridgeSpecify: 'Tell us more', bridgeSpecifySub: 'Different situations need different licenses',
    bridgeActivity: 'What will you do?', bridgeWhere: 'Where?', bridgeAgriLand: 'Is it on agricultural land?',
    bridgeForeignWorkers: 'Will you bring foreign workers?', bridgeCheckBtn: 'Check My Requirements',
    bridgeYes: 'Yes', bridgeNo: 'No', bridgeNotSure: 'Not Sure',
    bridgeVerdictYes: 'YES — You can do this', bridgeVerdictMaybe: 'CONDITIONALLY YES', bridgeVerdictNo: 'NOT ALLOWED',
    bridgeRequired: 'REQUIRED', bridgeRequiredSub: 'Must have before operating',
    bridgeRecommended: 'RECOMMENDED', bridgeRecommendedSub: 'Strongly advised',
    bridgeDept: 'Department', bridgeTimeline: 'Timeline', bridgeCost: 'Cost',
    bridgeTotalLicenses: 'Total licenses needed', bridgeTotalTime: 'Estimated total time',
    bridgeTotalCost: 'Estimated total cost', bridgeDownload: 'Download Full Checklist',
    bridgeAskAI: 'Ask Find.ai for Help', bridgeBack: 'Back',
    bridgeCNTrap: 'China Assumption Trap',
    bridgeNote: 'Advisory guide only. Requirements may vary by local authority. Consult a licensed advisor.',
    bridgeTimeline2: 'Typical Timeline',
    bridgeManufacturing: 'Manufacturing / Assembly', bridgeManufacturingDesc: 'Producing or assembling products',
    bridgeWarehouse: 'Warehouse / Storage', bridgeWarehouseDesc: 'Storing goods, logistics hub',
    bridgeChemical: 'Chemical / Hazardous', bridgeChemicalDesc: 'Working with chemicals',
    bridgeFoodProcessing: 'Food Processing', bridgeFoodProcessingDesc: 'Food manufacturing or packaging',
  },
  bm: {
    tools: 'Alat Hartanah',
    stampTitle: 'Kalkulator Duti Setem', stampDesc: 'Duti setem perjanjian sewa',
    yieldTitle: 'Kalkulator Pulangan Sewa', yieldDesc: 'Adakah hartanah anda berbaloi?',
    screenTitle: 'Saringan Penyewa', screenDesc: 'Semak risiko penyewa sebelum tandatangan',
    healthTitle: 'Semakan Perjanjian', healthDesc: 'Adakah perjanjian anda melindungi anda?',
    monthlyRent: 'Sewa Bulanan (RM)', leaseDuration: 'Tempoh Sewa',
    years: ['1 tahun', '2 tahun', '3 tahun', '5 tahun'],
    stampResult: 'Duti Setem Perlu Dibayar (SDSAS 2026)', stampExempt: 'Dikecualikan — tiada duti setem',
    stampNote: 'Perjanjian tanpa setem tidak boleh digunakan di mahkamah.',
    stampWho: 'Biasanya dibayar oleh penyewa, tetapi boleh dirunding.',
    stampDeadline: 'Mesti setem dalam 30 hari selepas tandatangan. Lewat = penalti sehingga 100%.',
    stampPerUnit: 'setiap unit RM250 sewa tahunan',
    sdsasNote: 'Sistem taksiran sendiri (SDSAS) berkuat kuasa Jan 2026. Pengecualian RM2,400 dimansuhkan. Anda kira dan bayar melalui MyTax.',
    oldDuty: 'Kadar Lama (Sebelum 2026)', dutyIncrease: 'Kenaikan',
    wasExempt: 'Sewa ini sebelum ini DIKECUALIKAN (bawah RM2,400/thn). Di bawah peraturan 2026, duti setem kini dikenakan.',
    vaultTitle: 'Bukti Foto', vaultDesc: 'Lindungi diri — tangkap, kunci, siap',
    vaultAddress: 'Nama Hartanah / Kondo', vaultAddressHint: 'cth. Lakefront Residence, Cyberjaya',
    vaultUnit: 'Nombor Unit', vaultType: 'Untuk apa ini?', vaultSelectType: 'Pilih satu',
    vaultCheckIn: 'Penyewa masuk', vaultCheckOut: 'Penyewa keluar', vaultDamage: 'Rakam kerosakan', vaultGeneral: 'Lain-lain',
    vaultUpload: 'Tambah Gambar', vaultUploadHint: 'Ambil gambar atau pilih dari galeri — kami kunci setiap satu supaya tak boleh dipertikaikan',
    vaultHashing: 'Mengunci gambar anda...', vaultPhotos: 'Gambar Anda', vaultHash: 'Perlindungan',
    vaultGenerate: 'Cipta Sijil Bukti', vaultVerified: 'DIKUNCI & DILINDUNGI',
    vaultCertId: 'No. Sijil', vaultDownload: 'Muat Turun Sijil Anda',
    vaultLegalNote: 'Sijil ini membuktikan gambar anda asli dan tidak diubah. Ia diterima di mahkamah Malaysia di bawah Akta Keterangan. Simpan gambar asal — jangan edit atau tukar nama.',
    annualRent: 'Sewa Tahunan', purchasePrice: 'Harga Belian (RM)',
    monthlyExpenses: 'Perbelanjaan Bulanan (RM)', expensesHint: 'Penyelenggaraan, insurans, cukai taksiran',
    grossYield: 'Pulangan Kasar', netYield: 'Pulangan Bersih',
    annualProfit: 'Untung Tahunan', monthlyProfit: 'Untung Bulanan',
    verdict: 'Keputusan',
    verdictGood: 'Pelaburan baik — melebihi purata pasaran',
    verdictOk: 'Sederhana — pertimbangkan potensi kenaikan nilai',
    verdictWeak: 'Di bawah purata — semak harga sewa atau perbelanjaan',
    calculate: 'Kira',
    tenantSalary: 'Gaji Bulanan Penyewa (RM)', rentAmount: 'Sewa Bulanan (RM)',
    jobType: 'Jenis Pekerjaan', occupants: 'Bilangan Penghuni', bedrooms: 'Bilik Tidur',
    moveReason: 'Sebab Pindah', hasGuarantor: 'Ada Penjamin?',
    jobs: { permanent: 'Tetap', contract: 'Kontrak', selfEmployed: 'Sendiri', unemployed: 'Menganggur/Pelajar' },
    reasons: { leaseEnd: 'Sewa tamat', work: 'Dekat tempat kerja', family: 'Sebab keluarga', evicted: 'Diusir', firstTime: 'Pertama kali sewa' },
    yes: 'Ya', no: 'Tidak', checkTenant: 'Saring Penyewa',
    riskLevel: 'Tahap Risiko', riskLow: 'RENDAH', riskMed: 'SEDERHANA', riskHigh: 'TINGGI',
    redFlags: 'Amaran', greenFlags: 'Positif', recommendation: 'Cadangan',
    affordability: 'Nisbah Kemampuan',
    checkAgreement: 'Semak Perjanjian', score: 'Skor Perjanjian', missing: 'Klausa Tiada', present: 'Ada',
    strong: 'KUAT — Dilindungi dengan baik', moderate: 'SEDERHANA — Ada jurang perlu diperbaiki', weak: 'LEMAH — Jurang besar, risiko tinggi',
    clauses: [
      { id: 'latePay', q: 'Klausa denda bayaran lewat?' },
      { id: 'deposit', q: 'Jumlah deposit dinyatakan (2+1)?' },
      { id: 'maintenance', q: 'Tanggungjawab penyelenggaraan dinyatakan?' },
      { id: 'sublet', q: 'Larangan sewa kecil?' },
      { id: 'earlyTermination', q: 'Klausa penamatan awal?' },
      { id: 'inventory', q: 'Senarai semak inventori masuk/keluar?' },
      { id: 'utility', q: 'Klausa pemindahan utiliti & bil akhir?' },
      { id: 'stampDuty', q: 'Tanggungjawab duti setem dinyatakan?' },
      { id: 'renewal', q: 'Terma pembaharuan dinyatakan?' },
      { id: 'dispute', q: 'Kaedah penyelesaian pertikaian?' },
    ],
    clauseFix: {
      latePay: 'Tambah: "Caj lewat 10% setahun atas baki tertunggak selepas 14 hari"',
      deposit: 'Tambah: "Deposit keselamatan 2 bulan sewa + 0.5 bulan deposit utiliti"',
      maintenance: 'Tambah: "Penyewa bertanggungjawab atas haus & lusuh. Tuan rumah bertanggungjawab atas struktur"',
      sublet: 'Tambah: "Penyewa tidak boleh menyewa kecil tanpa kebenaran bertulis"',
      earlyTermination: 'Tambah: "Mana-mana pihak boleh menamatkan dengan notis 2 bulan bertulis"',
      inventory: 'Tambah: "Inventori terperinci dengan gambar ditandatangani kedua-dua pihak"',
      utility: 'Tambah: "Penyewa perlu tukar nama utiliti dalam 14 hari"',
      stampDuty: 'Tambah: "Duti setem ditanggung oleh Penyewa"',
      renewal: 'Tambah: "Penyewa mempunyai hak pembaharuan pertama dengan notis 2 bulan"',
      dispute: 'Tambah: "Pertikaian dirujuk kepada mediasi sebelum mahkamah"',
    },
    trustTitle: 'Pautan Kepercayaan CN-MY', trustDesc: 'Sahkan syarikat China sebelum tandatangan sewa',
    usccLabel: 'Kod USCC 18 Digit', usccHint: 'Kod Kredit Sosial Bersepadu dari lesen perniagaan',
    usccInvalid: 'USCC tidak sah — mesti 18 aksara (huruf + nombor)',
    companyName: 'Nama Syarikat (中文)', companyNameEn: 'Nama Syarikat (English)',
    paidInCapital: 'Modal Berbayar (RMB)', taxRating: 'Penarafan Kredit Cukai',
    taxRatings: { A: 'Gred A — Cemerlang', B: 'Gred B — Baik', C: 'Gred C — Sederhana', D: 'Gred D — Lemah' },
    yearsOp: 'Tahun Beroperasi', bizScope: 'Skop Perniagaan',
    bizScopes: { manufacturing: 'Pembuatan', trading: 'Perdagangan', logistics: 'Logistik', tech: 'Teknologi', other: 'Lain-lain' },
    abnormalOps: 'Dalam Senarai Operasi Tidak Normal?',
    courtRecords: 'Rekod Mahkamah/Pertikaian?',
    generateReport: 'Jana Laporan Kepercayaan',
    trustGrade: 'Gred Kepercayaan', trustScore: 'Skor Kepercayaan',
    trustA: 'GRED A — Risiko Rendah. Selamat diteruskan.',
    trustB: 'GRED B — Sederhana. Teruskan dengan penjamin + deposit tambahan.',
    trustC: 'GRED C — Risiko Tinggi. Minta jaminan bank.',
    trustD: 'GRED D — Sangat Berisiko. Tidak digalakkan.',
    riskFactors: 'Faktor Risiko', positiveFactors: 'Faktor Positif',
    trustDisclaimer: 'Laporan nasihat sahaja. Bukan jaminan kredit. Sahkan semua maklumat secara bebas.',
    downloadReport: 'Muat Turun Laporan',
    trustLookup: 'Mencari syarikat...', trustFound: 'Syarikat dijumpai dalam pangkalan data',
    trustNotFound: 'Tiada dalam pangkalan data — masukkan butiran secara manual', trustAutoFill: 'Diisi automatik dari pangkalan data',
    trustManual: 'Kemasukan Manual', trustAuto: 'Carian Auto',
    trustRetry: 'Cuba Semula', trustOffline: 'Sambungan gagal — masukkan butiran secara manual',
    trafficGreen: 'LAMPU HIJAU — Selamat diteruskan', trafficYellow: 'LAMPU KUNING — Teruskan dengan berhati-hati', trafficRed: 'LAMPU MERAH — Risiko tinggi',
    navTitle: 'Navigator Situasi', navDesc: 'Panduan langkah demi langkah untuk pertikaian',
    navPick: 'Apa situasi anda?',
    navRentDefault: 'Sewa Tertunggak', navRentDefaultDesc: 'Penyewa tak bayar sewa',
    navDeposit: 'Pertikaian Deposit', navDepositDesc: 'Deposit tak dipulangkan',
    navEviction: 'Proses Pengusiran', navEvictionDesc: 'Perlu usir penyewa secara sah',
    navTimeline: 'Garis Masa', navCost: 'Anggaran Kos', navLaw: 'Asas Undang-undang',
    navStep: 'Langkah', navAction: 'Apa perlu buat', navWarning: 'Amaran',
    navDocument: 'Templat Dokumen', navCopyDoc: 'Salin Templat',
    navBack: 'Kembali ke situasi',
    bridgeTitle: 'Boleh Buat Ini?', bridgeDesc: 'Semakan pematuhan hartanah Malaysia',
    bridgePick: 'Apa yang anda mahu buat di Malaysia?', bridgePickSub: 'Pilih matlamat anda — kami tunjukkan semua yang perlu',
    bridgeRent: 'Sewa Hartanah', bridgeBuy: 'Beli Hartanah', bridgeOperate: 'Operasi Perniagaan',
    bridgeRentHouse: 'Sewa Rumah / Kondo', bridgeRentHouseDesc: 'Sewaan kediaman sebagai warga asing',
    bridgeRentOffice: 'Sewa Pejabat / Kedai', bridgeRentOfficeDesc: 'Sewa komersial untuk perniagaan',
    bridgeRentFactory: 'Sewa Kilang / Gudang', bridgeRentFactoryDesc: 'Sewa perindustrian untuk pembuatan',
    bridgeBuyHouse: 'Beli Rumah / Kondo', bridgeBuyHouseDesc: 'Syarat pemilikan asing',
    bridgeBuyLand: 'Beli Tanah', bridgeBuyLandDesc: 'Pertanian, pembangunan, kosong',
    bridgeOpenFnb: 'Buka Restoran / F&B', bridgeOpenFnbDesc: 'Pelesenan perniagaan makanan',
    bridgeSetupFactory: 'Tubuhkan Kilang', bridgeSetupFactoryDesc: 'Operasi pembuatan',
    bridgeSpecify: 'Beritahu kami lagi', bridgeSpecifySub: 'Situasi berbeza perlukan lesen berbeza',
    bridgeActivity: 'Apa yang akan anda buat?', bridgeWhere: 'Di mana?', bridgeAgriLand: 'Adakah di atas tanah pertanian?',
    bridgeForeignWorkers: 'Akan bawa pekerja asing?', bridgeCheckBtn: 'Semak Keperluan Saya',
    bridgeYes: 'Ya', bridgeNo: 'Tidak', bridgeNotSure: 'Tidak Pasti',
    bridgeVerdictYes: 'YA — Anda boleh buat ini', bridgeVerdictMaybe: 'YA BERSYARAT', bridgeVerdictNo: 'TIDAK DIBENARKAN',
    bridgeRequired: 'WAJIB', bridgeRequiredSub: 'Mesti ada sebelum beroperasi',
    bridgeRecommended: 'DISYORKAN', bridgeRecommendedSub: 'Sangat digalakkan',
    bridgeDept: 'Jabatan', bridgeTimeline: 'Garis Masa', bridgeCost: 'Kos',
    bridgeTotalLicenses: 'Jumlah lesen diperlukan', bridgeTotalTime: 'Anggaran jumlah masa',
    bridgeTotalCost: 'Anggaran jumlah kos', bridgeDownload: 'Muat Turun Senarai Penuh',
    bridgeAskAI: 'Tanya Find.ai', bridgeBack: 'Kembali',
    bridgeCNTrap: 'Perangkap Andaian China',
    bridgeNote: 'Panduan nasihat sahaja. Keperluan mungkin berbeza mengikut pihak berkuasa tempatan.',
    bridgeTimeline2: 'Garis Masa Biasa',
    bridgeManufacturing: 'Pembuatan / Pemasangan', bridgeManufacturingDesc: 'Menghasilkan atau memasang produk',
    bridgeWarehouse: 'Gudang / Penyimpanan', bridgeWarehouseDesc: 'Menyimpan barang, hab logistik',
    bridgeChemical: 'Kimia / Berbahaya', bridgeChemicalDesc: 'Bekerja dengan bahan kimia',
    bridgeFoodProcessing: 'Pemprosesan Makanan', bridgeFoodProcessingDesc: 'Pengilangan atau pembungkusan makanan',
  },
  zh: {
    tools: '房产工具',
    stampTitle: '印花税计算器', stampDesc: '租约印花税',
    yieldTitle: '租金回报计算器', yieldDesc: '您的房产值得投资吗？',
    screenTitle: '租客筛查', screenDesc: '签约前检查租客风险',
    healthTitle: '协议健康检查', healthDesc: '您的协议是否保护您？',
    monthlyRent: '月租金 (RM)', leaseDuration: '租约期限',
    years: ['1年', '2年', '3年', '5年'],
    stampResult: '应付印花税 (SDSAS 2026)', stampExempt: '豁免 — 无需缴纳印花税',
    stampNote: '未盖章的协议不能在法庭上作为证据。',
    stampWho: '通常由租客支付，但可协商。',
    stampDeadline: '签约后30天内必须盖章。逾期 = 最高100%罚款。',
    stampPerUnit: '每RM250年租单位',
    sdsasNote: '自我评估系统（SDSAS）2026年1月生效。RM2,400豁免已取消。您需通过MyTax自行计算和缴付。',
    oldDuty: '旧规则（2026年前）', dutyIncrease: '涨幅',
    wasExempt: '此租金之前获豁免（低于RM2,400/年）。2026年新规下，现需缴纳印花税。',
    vaultTitle: '照片证明', vaultDesc: '保护自己 — 拍照、锁定、完成',
    vaultAddress: '房产/公寓名称', vaultAddressHint: '例：Lakefront Residence, Cyberjaya',
    vaultUnit: '单位号', vaultType: '这是用于什么？', vaultSelectType: '选择一个',
    vaultCheckIn: '租客入住', vaultCheckOut: '租客退房', vaultDamage: '记录损坏', vaultGeneral: '其他',
    vaultUpload: '添加照片', vaultUploadHint: '拍照或从相册选择 — 我们会锁定每张照片，确保无法被争议',
    vaultHashing: '正在锁定您的照片...', vaultPhotos: '您的照片', vaultHash: '保护方式',
    vaultGenerate: '创建证明证书', vaultVerified: '已锁定和保护',
    vaultCertId: '证书编号', vaultDownload: '下载您的证书',
    vaultLegalNote: '本证书证明您的照片为原始照片且未被篡改。它依据马来西亚证据法在法庭上被接受。请妥善保管原始照片 — 不要编辑或重命名。',
    annualRent: '年租金', purchasePrice: '购买价格 (RM)',
    monthlyExpenses: '每月支出 (RM)', expensesHint: '管理费、保险、门牌税、地税',
    grossYield: '毛回报率', netYield: '净回报率',
    annualProfit: '年净利润', monthlyProfit: '月净利润',
    verdict: '评估',
    verdictGood: '好投资 — 高于市场平均',
    verdictOk: '一般 — 考虑升值潜力',
    verdictWeak: '低于平均 — 检查租金或支出',
    calculate: '计算',
    tenantSalary: '租客月薪 (RM)', rentAmount: '月租金 (RM)',
    jobType: '就业类型', occupants: '住户人数', bedrooms: '卧室数量',
    moveReason: '搬迁原因', hasGuarantor: '有担保人？',
    jobs: { permanent: '全职', contract: '合同', selfEmployed: '自雇', unemployed: '无业/学生' },
    reasons: { leaseEnd: '租约到期', work: '靠近工作', family: '家庭原因', evicted: '被驱逐', firstTime: '首次租房' },
    yes: '是', no: '否', checkTenant: '筛查租客',
    riskLevel: '风险等级', riskLow: '低风险', riskMed: '中等风险', riskHigh: '高风险',
    redFlags: '警告', greenFlags: '优点', recommendation: '建议',
    affordability: '负担能力比',
    checkAgreement: '检查协议', score: '协议评分', missing: '缺失条款', present: '已有',
    strong: '强 — 保护良好', moderate: '中等 — 需要修补', weak: '弱 — 重大漏洞，高风险',
    clauses: [
      { id: 'latePay', q: '逾期付款罚款条款？' },
      { id: 'deposit', q: '押金金额明确（2+1）？' },
      { id: 'maintenance', q: '维修责任明确？' },
      { id: 'sublet', q: '禁止转租条款？' },
      { id: 'earlyTermination', q: '提前终止条款？' },
      { id: 'inventory', q: '入住/退房清单？' },
      { id: 'utility', q: '水电转名及最终账单条款？' },
      { id: 'stampDuty', q: '印花税责任明确？' },
      { id: 'renewal', q: '续约条款？' },
      { id: 'dispute', q: '争议解决方式？' },
    ],
    clauseFix: {
      latePay: '添加："逾期14天后按年利率10%收取滞纳金"',
      deposit: '添加："押金为2个月租金 + 0.5个月水电押金"',
      maintenance: '添加："租客负责日常损耗，房东负责结构性维修"',
      sublet: '添加："未经书面同意，租客不得转租"',
      earlyTermination: '添加："任何一方可提前2个月书面通知终止"',
      inventory: '添加："双方签署附照片的详细清单"',
      utility: '添加："租客须在14天内将水电转至本人名下"',
      stampDuty: '添加："印花税由租客承担"',
      renewal: '添加："租客有优先续约权，需提前2个月通知"',
      dispute: '添加："争议先提交调解再诉诸法院"',
    },
    trustTitle: '中马信任链接', trustDesc: '签约前验证中国公司资质',
    usccLabel: '18位统一社会信用代码', usccHint: '营业执照上的统一社会信用代码',
    usccInvalid: '无效USCC — 必须为18位字符（字母+数字）',
    companyName: '公司名称（中文）', companyNameEn: '公司名称（英文）',
    paidInCapital: '实缴资本（人民币）', taxRating: '纳税信用等级',
    taxRatings: { A: 'A级 — 优秀', B: 'B级 — 良好', C: 'C级 — 一般', D: 'D级 — 较差' },
    yearsOp: '运营年限', bizScope: '经营范围',
    bizScopes: { manufacturing: '制造业', trading: '贸易', logistics: '物流', tech: '科技', other: '其他' },
    abnormalOps: '是否在经营异常名录？',
    courtRecords: '是否有法院/法律纠纷？',
    generateReport: '生成信任报告',
    trustGrade: '信任等级', trustScore: '信任分数',
    trustA: 'A级 — 低风险。可安全签约。',
    trustB: 'B级 — 中等风险。建议增加担保人和额外押金。',
    trustC: 'C级 — 较高风险。要求银行担保。',
    trustD: 'D级 — 高风险。不建议签约。',
    riskFactors: '风险因素', positiveFactors: '积极因素',
    trustDisclaimer: '仅供参考。非信用担保。签约前请独立核实所有信息。',
    downloadReport: '下载信任报告',
    trustLookup: '正在查询公司...', trustFound: '已在数据库中找到公司',
    trustNotFound: '未在数据库中找到 — 请手动输入信息', trustAutoFill: '已从数据库自动填充',
    trustManual: '手动输入', trustAuto: '自动查询',
    trustRetry: '重试', trustOffline: '连接失败 — 请手动输入信息',
    trafficGreen: '绿灯 — 可安全签约', trafficYellow: '黄灯 — 需谨慎行事', trafficRed: '红灯 — 高风险',
    navTitle: '情况导航', navDesc: '房产纠纷分步指南',
    navPick: '您面临什么情况？',
    navRentDefault: '租金拖欠', navRentDefaultDesc: '租客未缴租金',
    navDeposit: '押金纠纷', navDepositDesc: '押金未退还或不合理扣除',
    navEviction: '驱逐流程', navEvictionDesc: '需要合法驱逐租客',
    navTimeline: '时间线', navCost: '预估费用', navLaw: '法律依据',
    navStep: '步骤', navAction: '该怎么做', navWarning: '警告',
    navDocument: '文件模板', navCopyDoc: '复制模板',
    navBack: '返回情况列表',
    bridgeTitle: '马来西亚办事攻略', bridgeDesc: '租房·买房·开业 — 一站式合规查询',
    bridgePick: '您想在马来西亚做什么？', bridgePickSub: '选择您的目标 — 我们会展示您需要的一切',
    bridgeRent: '租赁房产', bridgeBuy: '购买房产', bridgeOperate: '经营业务',
    bridgeRentHouse: '租住宅/公寓', bridgeRentHouseDesc: '外国人住宅租赁',
    bridgeRentOffice: '租办公室/店铺', bridgeRentOfficeDesc: '商业租赁',
    bridgeRentFactory: '租工厂/仓库', bridgeRentFactoryDesc: '工业租赁用于制造',
    bridgeBuyHouse: '买住宅/公寓', bridgeBuyHouseDesc: '外国人购房要求',
    bridgeBuyLand: '买土地', bridgeBuyLandDesc: '农业、开发、空地',
    bridgeOpenFnb: '开餐厅/餐饮', bridgeOpenFnbDesc: '食品经营许可',
    bridgeSetupFactory: '建厂', bridgeSetupFactoryDesc: '制造业运营',
    bridgeSpecify: '告诉我们更多', bridgeSpecifySub: '不同情况需要不同许可证',
    bridgeActivity: '您要做什么？', bridgeWhere: '在哪里？', bridgeAgriLand: '是否在农业用地上？',
    bridgeForeignWorkers: '是否带外劳？', bridgeCheckBtn: '检查我的要求',
    bridgeYes: '是', bridgeNo: '否', bridgeNotSure: '不确定',
    bridgeVerdictYes: '可以 — 您能做这个', bridgeVerdictMaybe: '有条件可以', bridgeVerdictNo: '不允许',
    bridgeRequired: '必需', bridgeRequiredSub: '运营前必须具备',
    bridgeRecommended: '建议', bridgeRecommendedSub: '强烈建议',
    bridgeDept: '部门', bridgeTimeline: '时间线', bridgeCost: '费用',
    bridgeTotalLicenses: '所需许可证总数', bridgeTotalTime: '预计总时间',
    bridgeTotalCost: '预计总费用', bridgeDownload: '下载完整清单',
    bridgeAskAI: '咨询Find.ai', bridgeBack: '返回',
    bridgeCNTrap: '中国思维陷阱',
    bridgeNote: '仅供参考。要求可能因当地主管部门而异。请咨询持牌顾问。',
    bridgeTimeline2: '典型时间线',
    bridgeManufacturing: '制造/组装', bridgeManufacturingDesc: '生产或组装产品',
    bridgeWarehouse: '仓储', bridgeWarehouseDesc: '存储货物、物流中心',
    bridgeChemical: '化学/危险品', bridgeChemicalDesc: '处理化学品',
    bridgeFoodProcessing: '食品加工', bridgeFoodProcessingDesc: '食品制造或包装',
  },
};
